Repository Occulus-Server/Occulus-Eris, pull requests merged in 2020-11, with the labels that each got.

#1 The First Big Upstream Update
  code/__DEFINES/perks.dm
  code/controllers/subsystems/jobs.dm
  code/controllers/subsystems/staverbs.dm
  code/datums/mob_stats.dm
  code/datums/perks/fate.dm
  code/datums/perks/job.dm
  code/datums/perks/oddity.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/alarm.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/machinery/excelsior/ex_teleporter.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/objects/items/weapons/implant/implants/carrion/control_spider.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/modules/client/preferences.dm
  code/modules/clothing/clothing_accessories.dm
  code/modules/clothing/gloves/stungloves.dm
  code/modules/clothing/head/armor.dm
  code/modules/core_implant/core_implant.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/core_implant/module.dm
  code/modules/hydroponics/grown.dm
  code/modules/mechs/equipment/combat.dm
  code/modules/mechs/mech_interaction.dm
  code/modules/mob/death.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/modular_computers/file_system/programs/antagonist/revelation.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/internal/bones.dm
  code/modules/power/apc.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/research/designs/mechs2/exosuits_equipment.dm
  code/modules/research/nodes/robotics.dm
  code/modules/research/rdconsole.dm
  html/changelogs/CeUvi-new-tech-sprotes.yml
  icons/inventory/feet/icon.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mechs/mech_equipment.dmi
  icons/mechs/mech_weapon_overlays.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand.dmi
  icons/mob/light_overlays.dmi
  icons/obj/forensics.dmi
  icons/obj/guns/energy/egun.dmi
  icons/obj/light_overlays.dmi
  icons/obj/tank.dmi
  icons/obj/weapons.dmi
  nano/templates/centrifuge.tmpl
  nano/templates/sanity.tmpl
Labels: Bugfix, Quality of Life, Sprites, Upstream Update, ⚠️ Severity: S-5 Trivial, 👥 Impact: I-1 All

#3 Added export prices for a large number of reagents
  cev_eris.dme
  code/datums/ai_law_sets.dm
  zzzz_modular_occulus/code/modules/economy/price_list_reagents.dm
  zzzz_modular_occulus/code/modules/loot_spawn_blacklist.dm
  zzzz_modular_occulus/code/modules/reagents/recipes.dm
Labels: Balance/Rebalance, Bugfix, ⚠️ Severity: S-5 Trivial, 👥 Impact: I-4 Few

#4 Backports some gun PRs from upstream that we missed
  cev_eris.dme
  code/datums/craft/recipes/weapon.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/lasersmg.dm
  code/modules/projectiles/guns/energy/shrapnel.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/automatic/zoric.dm
  code/modules/projectiles/guns/projectile/pistol/avasarala.dm
  code/modules/projectiles/guns/projectile/pistol/paco.dm
  code/modules/projectiles/guns/projectile/shotgun/bojevic.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/regulator.dm
  code/modules/projectiles/projectile/bullettypes.dm
  icons/obj/guns/energy/lasersmg.dmi
Labels: Balance/Rebalance, Feature, Quality of Life, Sprites, ⚠️ Severity: S-4 Minor, 👥 Impact: I-1 All

#5 Crew Records Fixes (AKA: ALT TITLES NOW WORK!!!!!!)
  code/controllers/subsystems/jobs.dm
  code/game/jobs/job/assistant.dm
  code/modules/modular_computers/file_system/reports/crew_record.dm
Labels: Bugfix, Priority: High, ⚠️ Severity: S-4 Minor, 👥 Impact: I-1 All

#6 Changes resting so that you should prooobably only need one cup/meal of a desire to level up.
  code/modules/sanity/sanity_mob.dm
Labels: Balance/Rebalance, Quality of Life, ⚠️ Severity: S-5 Trivial, 👥 Impact: I-1 All

#14 replaces the catwalks in the church bioreactor room with regular floor
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Quality of Life

#8 Nerfs Herald Breakdown
  code/modules/sanity/breakdowns.dm
Labels: Balance/Rebalance, Pending Community Discussion/Vote, Quality of Life

#9 Olivaw Resprite
  cev_eris.dme
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  zzzz_modular_occulus/icons/obj/guns/projectile/olivawcivil.dmi
Labels: Modular, Ready to Merge, Sprites

#11 Removes the debug fallback Core Implant selection
  code/datums/setup_option/core_implants.dm
Labels: Code Cleanup, Ready to Merge

#13 Upstream Patch to make circular saws and reinforced platings not overly common
  code/__DEFINES/spawner.dm
  code/game/objects/items/weapons/tools/crowbars.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/items/weapons/tools/saws.dm
  code/game/objects/items/weapons/tools/scalpels.dm
  code/game/objects/items/weapons/tools/screwdrivers.dm
  code/game/objects/items/weapons/tools/shovel.dm
  code/game/objects/items/weapons/tools/tape.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/game/objects/items/weapons/tools/wrenches.dm
  code/game/objects/random/tools.dm
  code/modules/research/experiment.dm
Labels: Balance/Rebalance, Ready to Merge, Upstream Update

#15 Adjusted a number of job stats to have less eregius outliers
  cev_eris.dme
  zzzz_modular_occulus/code/game/jobs/job/job.dm
Labels: Balance/Rebalance, Modular, Quality of Life, Ready to Merge, ⚠️ Severity: S-4 Minor, 👥 Impact: I-3 Some

#16 Removed Law 5 as per Emojicracy
  code/datums/ai_law_sets.dm
Labels: Ready to Merge, Removal, ⚠️ Severity: S-5 Trivial, 👥 Impact: I-5 Minimal

#17 Oddities and Faction items lore update
  zzzz_modular_occulus/code/modules/game/Objects/Items/Devices/artifacts.dm
  zzzz_modular_occulus/code/modules/game/Objects/Items/oddities.dm
Labels: Lore Compliance, Modular, Quality of Life, Ready to Merge, ⚠️ Severity: S-5 Trivial, 👥 Impact: I-5 Minimal

#19 removed toxin damage from toxic revenger
  code/datums/perks/oddity.dm
Labels: Balance/Rebalance, Quality of Life, Ready to Merge, 👥 Impact: I-5 Minimal

#18 Added fiber tape to advanced tool disks
  cev_eris.dme
  code/game/objects/random/packs.dm
  code/game/objects/structures/crates_lockers/closets/maint_loot.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/autolathe_disks.dm
  zzzz_modular_occulus/code/game/objects/random/utility.dm
Labels: Bugfix, Feature, Quality of Life, Ready to Merge, 👥 Impact: I-5 Minimal

#20 added music insight and desire.
  cev_eris.dme
  code/datums/sound_player.dm
  code/modules/sanity/sanity_mob.dm
  zzzz_modular_occulus/code/modules/sanity/sanity_mob.dm
Labels: Feature, Quality of Life, Ready to Merge, ⚠️ Severity: S-5 Trivial, 👥 Impact: I-5 Minimal

#26 Please Merge Immediately - DME update from server.
  cev_eris.dme
Labels: Priority: Critical

#29 changes propaganda chips to not scream lrp shit
  code/game/objects/items/devices/propaganda_chip.dm
Labels: Lore Compliance, Quality of Life, Ready to Merge

#21 Consolidates Locker Room, Showers, and Laundry into a Singular Sane Location
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Quality of Life, Ready to Merge

#27 Update club layout
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Ready to Merge

#28 Vendor Prices/Nerfs Dr. Gibb
  cev_eris.dme
  zzzz_modular_occulus/code/modules/economy/vending.dm
  zzzz_modular_occulus/code/modules/reagents/food-Drinks.dm
Labels: Balance/Rebalance, Ready to Merge

#24 Maps in 3 Universal Translators
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Ready to Merge

#31 adjusted blacklists
  zzzz_modular_occulus/code/modules/loot_spawn_blacklist.dm
Labels: Bugfix, Modular, Priority: High, Ready to Merge, ⚠️ Severity: S-3 Moderate, 👥 Impact: I-3 Some

#30 Fixes hivemind announcement delay
  code/game/gamemodes/events/hivemind_invasion.dm
Labels: Balance/Rebalance, Bugfix, Code Cleanup, Ready for review

#33 Correct grammar and lore on trade stations.
  code/modules/trade/datums/trade_stations_presets/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/fs_weapon_factory.dm
  code/modules/trade/datums/trade_stations_presets/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/suit_up.dm
  code/modules/trade/datums/trade_stations_presets/trash_refine.dm
  code/modules/trade/datums/trade_stations_presets/zarya.dm
Labels: Lore Compliance, Ready to Merge
