Repository Occulus-Server/Occulus-Eris, pull requests merged in 2021-12, with the labels that each got.

#769 Updates changelog workflows to only run on the main repo
  .github/workflows/compile_changelogs.yml
  .github/workflows/make_changelogs.yml
Labels: Administrative, Ready to Merge, Code Cleanup

#768 Hypospray refactor
  zzzz_modular_occulus/code/modules/reagents/reagent_containers/hypospray.dm
Labels: Quality of Life, Ready to Merge

#767 Fixed painkillers turning into super-hyperzine. Thank you Eris.
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Bugfix

#776 Fixes body scanners breaking from shrapnel
  code/game/machinery/adv_med.dm
Labels: Bugfix, Ready to Merge

#777 Skill Refactor
  cev_eris.dme
  code/controllers/subsystems/jobs.dm
  code/datums/setup_option/backgrounds/origin.dm
  code/game/jobs/job/captain.dm
  code/game/machinery/autolathe/artist_bench.dm
  code/game/objects/items/devices/techno_tribalism.dm
  code/modules/client/preference_setup/background/06_training.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/sanity/inspiration_component.dm
  zzzz_modular_occulus/code/datums/setup_option/backgrounds/origin.dm
  zzzz_modular_occulus/code/game/jobs/job/captain.dm
  zzzz_modular_occulus/code/game/jobs/job/church.dm
  zzzz_modular_occulus/code/game/jobs/job/civilian.dm
  zzzz_modular_occulus/code/game/jobs/job/engineering.dm
  zzzz_modular_occulus/code/game/jobs/job/guild.dm
  zzzz_modular_occulus/code/game/jobs/job/medical.dm
  zzzz_modular_occulus/code/game/jobs/job/science.dm
  zzzz_modular_occulus/code/game/jobs/job/security.dm
  zzzz_modular_occulus/code/game/objects/items/oddities.dm
  zzzz_modular_occulus/code/modules/game/Objects/Items/oddities.dm
Labels: Feature, Ready for review, Administrative, Balance/Rebalance, Bugfix

#747 Sirenmobs+ Story teller event
  cev_eris.dme
  zzzz_modular_occulus/code/game/gamemodes/events/siren_scan.dm
  zzzz_modular_occulus/code/game/gamemodes/events/weather/siren_scan.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/augmentor.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/composer.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/conservator.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/replicant.dm
  zzzz_modular_occulus/code/modules/projectiles/projectile/projectile.dm
  zzzz_modular_occulus/icons/mob/siren/augmentor.dmi
  zzzz_modular_occulus/icons/mob/siren/composer.dmi
  zzzz_modular_occulus/icons/mob/siren/conservator.dmi
  zzzz_modular_occulus/icons/mob/siren/replicant.dmi
  zzzz_modular_occulus/maps/occulus_areas.dm
  zzzz_modular_occulus/sound/ambience/scaryambience.ogg
  zzzz_modular_occulus/sound/effects/The_Siren.wav
  zzzz_modular_occulus/sound/effects/screech.wav
  zzzz_modular_occulus/sound/effects/solonely.wav
  zzzz_modular_occulus/sound/effects/whispers.wav
  zzzz_modular_occulus/sound/voice/replicanthum.wav
  zzzz_modular_occulus/sound/voice/roboticactivation.wav
Labels: Feature, Sprites, Modular, Code Feature, Audio

#779 hot fix for siren scan event
  zzzz_modular_occulus/code/game/gamemodes/events/siren_scan.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/replicant.dm
Labels: Priority: High, ⚠️ Severity: S-0 Showstopper, Bugfix, Ready to Merge

#783 Fixes an occasional runtime
  zzzz_modular_occulus/code/modules/economy/price_list_fixed.dm
Labels: Bugfix, Ready to Merge

#780 fixes noble and merchant perks
  code/datums/perks/fate.dm
  code/modules/economy/cash.dm
  zzzz_modular_occulus/code/modules/long_range_scanner/long_range_scanner.dm
  zzzz_modular_occulus/code/modules/sanity/sanity_mob.dm
Labels: Balance/Rebalance, Bugfix

#774 Modifies the Liberty
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/revolver/saa.dm
Labels: Balance/Rebalance

#786 hotfix: point buy system
  code/modules/client/preference_setup/background/06_training.dm
Labels: Priority: High, Bugfix, Ready to Merge

#731 First part of the occultist totem/monolith update. DO NOT MERGE!!
  cev_eris.dme
  code/__DEFINES/perks.dm
  code/modules/sanity/breakdown.dm
  zzzz_modular_occulus/code/datums/perks/oddity.dm
  zzzz_modular_occulus/code/game/gamemodes/occultist/occultist_machines.dm
  zzzz_modular_occulus/code/game/gamemodes/occultist/occultist_mind.dm
  zzzz_modular_occulus/code/game/gamemodes/occultist/occultist_powers.dm
  zzzz_modular_occulus/code/game/turfs/flooring/flooring.dm
  zzzz_modular_occulus/icons/turf/occult/flooring/floor.dmi
  zzzz_modular_occulus/icons/turf/occult/totems.dmi
Labels: Ready for review, Framework Addition

#784 Fixes Soaruim/LDM tossing anchored stuff
  zzzz_modular_occulus/code/modules/reagents/reagentprocs.dm
Labels: Bugfix, Ready to Merge

#788 Updates ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: Administrative, Ready to Merge, Github/Discord

#790 Update flavor.dm
  code/_global_vars/lists/flavor.dm
Labels: Quality of Life, Ready to Merge

#791 Aegis gear updoot
  cev_eris.dme
  icons/inventory/back/mob.dmi
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/objects/items/weapons/storage/belt.dm
  zzzz_modular_occulus/code/modules/clothing/suit/suits.dm
  zzzz_modular_occulus/code/modules/clothing/under/jobs/security.dm
  zzzz_modular_occulus/icons/inventory/suit/icon.dmi
  zzzz_modular_occulus/icons/inventory/suit/mob.dmi
  zzzz_modular_occulus/icons/inventory/uniform/icon.dmi
  zzzz_modular_occulus/icons/inventory/uniform/mob.dmi
  zzzz_modular_occulus/icons/obj/weapons.dmi
Labels: Balance/Rebalance, Map Changes, Ready to Merge, Code Feature

#794 Comments projectile miss pending rework
  code/modules/projectiles/projectile.dm
Labels: Bug, Ready for review, Removal

#793 Composers no longer do audio loops while dead
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/composer.dm
Labels: Ready for review, Bugfix

#792 Fixed a lot of sanity and insight items.
  code/game/machinery/autolathe/artist_bench.dm
  code/game/objects/items/devices/techno_tribalism.dm
  code/modules/client/preference_setup/background/06_training.dm
  zzzz_modular_occulus/code/game/machinery/jukebox.dm
  zzzz_modular_occulus/code/game/objects/items/toys/balls.dm
  zzzz_modular_occulus/code/game/objects/structures/fitness.dm
  zzzz_modular_occulus/code/modules/sanity/sanity_mob.dm
Labels: Bugfix, Ready to Merge

#798 Fixes NSA overdosing caused by Ares
  zzzz_modular_occulus/code/modules/reagents/reagent_containers/hypovial.dm
Labels: Ready for review, Bugfix

#797 Object blacklistings
  zzzz_modular_occulus/code/modules/clothing/suit/suits.dm
  zzzz_modular_occulus/prosthesis/prosthesis_parts.dm
Labels: Bugfix, Ready to Merge
