Repository Occulus-Server/Occulus-Eris, pull requests merged in 2021-11, with the labels that each got.

#750 Adds auxtools debugging
  SpacemanDMM.toml
  cev_eris.dme
  code/__HELPERS/debugger.dm
Labels: Administrative, Ready to Merge

#751 Four small changes.
  cev_eris.dme
  code/datums/repositories/crew/binary.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/items/weapons/storage/misc.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/overmap-eris.dm
  zzzz_modular_occulus/code/datum/craft/recipes/tools.dm
  zzzz_modular_occulus/icons/obj/food.dmi
Labels: Feature, Quality of Life, Balance/Rebalance, Bugfix, Ready to Merge

#752 Lethal Spiderlings Warning (Ready for Review)
  cev_eris.dme
  code/modules/sanity/sanity_lists.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/implant/implants/carrion/carrion_spiders.dm
Labels: Balance/Rebalance, Changes Requested

#694 Discord Bot v0.2.0
  zzzz_modular_occulus/bin/.gitignore
  zzzz_modular_occulus/bin/bot/Cargo.lock
  zzzz_modular_occulus/bin/bot/Cargo.toml
  zzzz_modular_occulus/bin/bot/src/bot/commands/admin.rs
  zzzz_modular_occulus/bin/bot/src/bot/commands/general.rs
  zzzz_modular_occulus/bin/bot/src/bot/commands/mod.rs
  zzzz_modular_occulus/bin/bot/src/bot/commands/quotes.rs
  zzzz_modular_occulus/bin/bot/src/bot/framework.rs
  zzzz_modular_occulus/bin/bot/src/bot/mod.rs
  zzzz_modular_occulus/bin/bot/src/bot/quotes.rs
  zzzz_modular_occulus/bin/bot/src/bot/rpc.rs
  zzzz_modular_occulus/bin/bot/src/main.rs
  zzzz_modular_occulus/bin/byond-socks.so
  zzzz_modular_occulus/bin/connlib/go.mod
  zzzz_modular_occulus/bin/connlib/main.go
  zzzz_modular_occulus/bin/make.sh
Labels: Administrative, Ready to Merge, Framework Addition

#757 crusade daggers are now spawn blacklisted
  zzzz_modular_occulus/code/modules/core_implant/cruciform/rituals/base.dm
Labels: Bugfix, Ready to Merge

#756 fixes AMR
  code/modules/projectiles/guns/projectile/sniper.dm
Labels: Bugfix, Ready to Merge

#755 Tiny recipe tweak
  zzzz_modular_occulus/code/datum/craft/recipes/tools.dm
Labels: Balance/Rebalance, Ready to Merge

#601 Roundstart Slimepeople
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/species/station/slime.dm
  code/modules/organs/external/organ_icon.dm
  code/modules/sprite_accessories/extra.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/species/station.dm
Labels: Feature

#758 Updates the code to work with 514
  cev_eris.dme
  code/ZAS/Airflow.dm
  code/__DEFINES/_extools_api.dm
  code/__DEFINES/callbacks.dm
  code/__DEFINES/tick.dm
  code/_global_vars/misc.dm
  code/controllers/configuration.dm
  code/controllers/master.dm
  code/controllers/subsystems/air.dm
  code/datums/datum_hud.dm
  code/modules/admin/verbs/diagnostics.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/admin/verbs/ticklag.dm
  code/modules/client/client_defines.dm
  code/modules/mob/mob.dm
  code/world.dm
  config/example/config.txt
  html/add2changelog.html
  html/templates/footer.html
  html/templates/header.html
Labels: Upstream Update, Ready for review, Bugfix

#759 Small fixes from upstream
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/roach/life.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Upstream Update, Ready for review, Bugfix

#760 Fixes slime hair alpha
  code/modules/mob/living/carbon/human/update_icons.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/species/station.dm
Labels: Ready for review, Bugfix

#761 Adds Two New Nanite Weapons (Black Talon, Grey Claw). Code adjust to White Nail.
  code/modules/projectiles/guns/projectile.dm
  icons/mob/screen/gun_actions.dmi
  zzzz_modular_occulus/code/modules/gunwieldingnoises.dm
  zzzz_modular_occulus/code/modules/projectiles/ammunition/bullets.dm
  zzzz_modular_occulus/code/modules/projectiles/ammunition/magazines.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/rifle/whitenail.dm
  zzzz_modular_occulus/code/modules/projectiles/projectile/bullettypes.dm
  zzzz_modular_occulus/code/modules/research/designs.dm
  zzzz_modular_occulus/code/modules/research/nodes/combat.dm
  zzzz_modular_occulus/icons/obj/guns/projectile/blacktalon.dmi
  zzzz_modular_occulus/icons/obj/guns/projectile/greyclaw.dmi
  zzzz_modular_occulus/icons/obj/guns/projectile/whitenail.dmi
  zzzz_modular_occulus/icons/obj/magazines.dmi
  zzzz_modular_occulus/sound/weapons/guns/fire/claw_fire.ogg
  zzzz_modular_occulus/sound/weapons/guns/fire/talon_fire.ogg
  zzzz_modular_occulus/sound/weapons/guns/misc/wieldingnoises/claw_wield.ogg
  zzzz_modular_occulus/sound/weapons/guns/misc/wieldingnoises/nail_wield.ogg
  zzzz_modular_occulus/sound/weapons/guns/misc/wieldingnoises/talon_wield.ogg
Labels: Feature, Sprites, Modular, Ready to Merge

#763 Mech Manual Maintenance Mode External Extravaganza
  code/modules/mechs/mech_interaction.dm
Labels: Quality of Life, Ready to Merge

#762 fixed a number of minor things
  code/datums/perks/perk.dm
  code/game/jobs/job/security.dm
  code/modules/sanity/sanity_mob.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Balance/Rebalance, Bugfix, Ready to Merge
