Repository Occulus-Server/Occulus-Eris, pull requests merged in 2021-05, with the labels that each got.

#433 Horseshoes
  cev_eris.dme
  zzzz_modular_occulus/code/modules/clothing/shoes/horseshoes.dm
  zzzz_modular_occulus/code/modules/loadout/lists/shoes.dm
  zzzz_modular_occulus/icons/obj/horseshoes.dmi
Labels: Changes Requested, Feature, Quality of Life

#430 Jamini ports 6001
  code/game/antagonist/alien/borer.dm
  code/game/atoms_movable.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/clothing/spacesuits/rig/modules/computer.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/economy/price_list.dm
  code/modules/hivemind/mobs.dm
  code/modules/mob/living/simple_animal/borer/borer.dm
  code/modules/modular_computers/file_system/programs/generic/email_client.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/mob/hivemind.dmi
  icons/obj/module.dmi
  icons/obj/rig_modules.dmi
Labels: Administrative, Balance/Rebalance, Ready for review, Upstream Update

#434 Jamini ports 6021 - 6041
  code/datums/autolathe/biomatter.dm
  code/datums/music_tracks/engage.dm
  code/datums/uplink/stealth and camouflage items.dm
  code/game/objects/items/devices/hacktool.dm
  code/game/objects/items/weapons/design_disks/NeoTheology.dm
  code/game/objects/items/weapons/design_disks/autolathe_disks.dm
  code/game/objects/structures/girders.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/neotheology.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mob/living/living_defense.dm
  code/modules/overmap/exoplanets/planet_types/grass.dm
  code/modules/random_map/_random_map_setup.dm
  code/modules/random_map/noise/ore.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/mob/rig_back.dmi
  icons/obj/rig_modules.dmi
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/mekhane.dm
Labels: Balance/Rebalance, Bugfix, Feature, Quality of Life, Ready for review, Upstream Update

#425 [DNM] portoscar, part nine
  maps/CEVEris/Port_Oscar.dmm
Labels: DO NOT MERGE!!

#440 Hotfix
  code/controllers/subsystems/tickets/tickets.dm
  code/modules/admin/verbs/adminhelp.dm
Labels: Bugfix, Priority: High, Ready for review

#448 Jamini ports finishline
  code/controllers/subsystems/trade.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/items/weapons/mine.dm
  code/game/objects/items/weapons/traps.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/turfs/simulated.dm
  code/modules/clothing/clothing.dm
  code/modules/reagents/recipes.dm
  code/modules/research/xenoarchaeology/artifact/effect.dm
  code/modules/research/xenoarchaeology/tools/anomaly_suit.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Balance/Rebalance, Quality of Life, Ready for review, Upstream Update

#450 Adjustments to various gun prices, stats, vendors
  cev_eris.dme
  zzzz_modular_occulus/code/game/machinery/vending.dm
  zzzz_modular_occulus/code/modules/economy/vending.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/gunpricetweak.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/pistol/mk4.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/rifle/levergun.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/rifle/sawnlevergun.dm
Labels: Balance/Rebalance, Modular, Quality of Life, Ready for review

#455 Aegis Antagonism
  cev_eris.dme
  code/game/jobs/job/guild.dm
  zzzz_modular_occulus/code/game/antagonist/station/traitor.dm
  zzzz_modular_occulus/code/game/jobs/job/church.dm
Labels: Balance/Rebalance, Quality of Life, Ready to Merge

#454 Full Body Prosthesis Construction
  cev_eris.dme
  code/game/machinery/bioprinter.dm
  icons/obj/surgery.dmi
  zzz_modular_syzygy/defib.dm
  zzzz_modular_occulus/code/modules/organs/external/subtypes/robotic.dm
  zzzz_modular_occulus/prosthesis/implementation.dm
  zzzz_modular_occulus/prosthesis/prosthesis_brands.dm
  zzzz_modular_occulus/prosthesis/prosthesis_parts.dm
Labels: Balance/Rebalance, Bugfix, Feature, Quality of Life, Ready to Merge

#457 Augmentors, Arm Guns and Aliterations Almighty!
  cev_eris.dme
  zzzz_modular_occulus/code/datums/uplink/implants.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/augmentor.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/automatic/armguns.dm
  zzzz_modular_occulus/icons/obj/augmentor.dmi
  zzzz_modular_occulus/icons/obj/guns/projectile/hurricane.dmi
  zzzz_modular_occulus/icons/obj/guns/projectile/tornado.dmi
  zzzz_modular_occulus/icons/obj/guns/projectile/typhoon.dmi
Labels: Feature, Modular

#453 port oscar, part 10
  maps/CEVEris/Port_Oscar.dmm
Labels: Map Changes

#451 Tweaks to armor and gun parts
  cev_eris.dme
  zzzz_modular_occulus/code/datums/craft/crafting_items.dm
Labels: Balance/Rebalance, Modular

#460 Multiple small tweaks to the map
  maps/CEVEris/_CEV_Eris.dmm
Labels: Balance/Rebalance, Bugfix, Map Changes, Ready for review

#462 Port Oscar: Now with atmos and a cooler chapel.
  maps/CEVEris/Port_Oscar.dmm
Labels: Map Changes, Ready for review

#463 A number of small path fixes and machinery tweaks
  cev_eris.dme
  code/datums/autolathe/guns.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/trade/datums/trade_stations_presets/fs_weapon_factory.dm
  zzzz_modular_occulus/code/game/machinery/tweaks.dm
  zzzz_modular_occulus/code/modules/loot_spawn_blacklist.dm
Labels: Bugfix, Feature, Quality of Life, Ready for review

#465 Fixes antag spam
  code/game/gamemodes/roleset/simple.dm
Labels: Bugfix

#469 Sanity adjustement
  code/modules/sanity/sanity_mob.dm
Labels: Bugfix, Quality of Life, Ready for review

#470 Cash Registers
  code/modules/economy/cash_register.dm
  code/modules/mechs/mech_interaction.dm
  icons/obj/stationobjs.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Bugfix, Feature, Map Changes, Ready to Merge, Sprites

#472 Fixed typos in MID Hecate description.
  zzzz_modular_occulus/code/modules/reagents/reagent_containers/hypospray.dm
Labels: Bugfix, Modular, Ready to Merge

#473 Fixes soygel sprite
  zzzz_modular_occulus/icons/obj/plush.dmi
Labels: Ready to Merge, Sprites

#474 One Star Lore Pass
  zzzz_modular_occulus/code/game/occulus-lore-fixes.dm
Labels: Lore Compliance, Ready to Merge

#477 New Space Ruins Map
  maps/encounters/spaceruins/spaceruins.dmm
Labels: Map Changes, Ready to Merge

#471 port oscar part 14: finishing bridge, optimizations, misc. maints changes
  maps/CEVEris/Port_Oscar.dmm
Labels: Bugfix, Map Changes, Ready for review

#476 Eris Ports 5 22 2021
  cev_eris.dme
  code/ATMOSPHERICS/atmospherics.dm
  code/controllers/subsystems/misc.dm
  code/datums/autolathe/circuits.dm
  code/datums/autolathe/guns.dm
  code/datums/craft/recipes/furniture.dm
  code/game/machinery/kitchen/microwave.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/circuitboards/computer/computer.dm
  code/game/objects/items/weapons/design_disks/autolathe_disks.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/modules/dungeons/junk_tractor_beam.dm
  code/modules/maps/tg/reader.dm
  code/modules/projectiles/guns/projectile/battle_rifle/kovacs.dm
  icons/mob/slimes.dmi
  icons/obj/food.dmi
  icons/obj/guns/projectile/kovacs.dmi
  icons/obj/kitchen.dmi
  icons/obj/structures/junk_tractor_beam.dmi
  maps/CEVEris/_CEV_Eris.dmm
  maps/encounters/junk_tractor_beam/junk_tractor_beam.dm
  maps/encounters/junk_tractor_beam/junk_tractor_beam.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral.dm
  maps/submaps/junk_field/j25_25/neutral/neutral1.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral2.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral3.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral.dm
  maps/submaps/junk_field/j5_5/neutral/neutral1.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral10.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral11.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral2.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral3.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral4.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral5.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral6.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral7.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral8.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral9.dmm
  maps/submaps/junk_field/junk_field.dm
  nano/templates/jtb_console.tmpl
  sound/effects/campfirecrackle.ogg
Labels: Ready for review, Upstream Update

#479 Fixed the bluespace tractor beam
  cev_eris.dme
  icons/obj/hydroponics_growing.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Bugfix, Map Changes, Ready to Merge, Upstream Update

#484 A number of small fixes done quickly
  cev_eris.dme
  code/game/machinery/autolathe/artist_bench.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/modules/reagents/recipes.dm
  code/modules/soulcrypt/holochip.dm
  zzzz_modular_occulus/code/game/machinery/autolathe/artist_bench.dm
  zzzz_modular_occulus/code/game/machinery/nanite_reconstitution_apparatus.dm
  zzzz_modular_occulus/code/game/objects/items/translators.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/augmentor.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/tools/mods/mod_types.dm
  zzzz_modular_occulus/code/modules/reagents/reagents/other.dm
  zzzz_modular_occulus/code/modules/research/designs.dm
  zzzz_modular_occulus/code/modules/research/nodes/biotech.dm
  zzzz_modular_occulus/code/modules/research/nodes/bluespace.dm
  zzzz_modular_occulus/code/modules/research/nodes/combat.dm
  zzzz_modular_occulus/code/modules/research/nodes/engineering.dm
  zzzz_modular_occulus/code/modules/research/nodes/illegal.dm
  zzzz_modular_occulus/code/modules/soulcrypt/holochip.dm
Labels: Balance/Rebalance, Bugfix, Feature, Modular, Quality of Life, Ready to Merge

#481 Part one of de-serbing mercs
  code/game/antagonist/outer/mercenary/merc_faction.dm
Labels: Lore Compliance, Ready to Merge

#487 Ports Signals from Upstream
  code/__DEFINES/components.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/game/area/areas.dm
  code/game/atoms_movable.dm
  code/game/machinery/alarm.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/objects/items.dm
  code/game/objects/items/_inventory.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mob/inventory.dm
  code/modules/power/apc.dm
Labels: Code Cleanup, Ready for review, Upstream Update

#485 Hand Retail Scanners
  cev_eris.dme
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/modules/economy/retail_scanner.dm
  zzzz_modular_occulus/icons/obj/device.dmi
Labels: Feature, Modular

#488 Ports shield updoots
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/organ_module/active/armshields.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/modules/cargo/exports/gear.dm
  code/modules/clothing/head/armor.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/superior_animal/roach/attack.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob.dm
  code/modules/random_map/drop/drop_types.dm
  icons/inventory/back/mob.dmi
Labels: Balance/Rebalance, Feature, Ready for review, Upstream Update

#489 Defaults hypospray to not use reagent scan
  zzzz_modular_occulus/code/modules/reagents/reagent_containers/hypospray.dm
Labels: Quality of Life, Ready for review

#483 Centcom remap
  maps/CEVEris/centcomm.dmm
Labels: Map Changes, Ready for review

#493 [WIP] eris ports 5 28 21 lol
  cev_eris.dme
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/circuitboards/machinery/beechinery.dm
  code/game/objects/items/weapons/circuitboards/machinery/chemistry.dm
  code/game/objects/items/weapons/design_disks/frozen_star.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/modules/cargo/packs.dm
  code/modules/hydroponics/beekeeping/beehive.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/research/designs/weapon.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/beekeeping.dmi
  icons/obj/grenade.dmi
  icons/obj/guns/breacher.dmi
  icons/obj/guns/energy/brigador.dmi
  icons/obj/guns/energy/decloner.dmi
  icons/obj/guns/energy/flora.dmi
  icons/obj/guns/energy/freezegun.dmi
  icons/obj/guns/energy/lascannon.dmi
  icons/obj/guns/energy/nucgun.dmi
  icons/obj/guns/energy/stunrevolver_moebius.dmi
  icons/obj/guns/energy/toxgun.dmi
  icons/obj/guns/launcher/rapidsyringegun.dmi
  icons/obj/guns/launcher/syringegun.dmi
  icons/obj/guns/projectile/ak/brushmaster.dmi
  icons/obj/guns/projectile/ak/excel.dmi
  icons/obj/guns/projectile/ak/kalash.dmi
  icons/obj/guns/projectile/ak/krinkov.dmi
  icons/obj/guns/projectile/ak/venger.dmi
  icons/obj/guns/projectile/ak/vipr.dmi
  icons/obj/guns/projectile/ak/wasp.dmi
  icons/obj/guns/projectile/c20m.dmi
  icons/obj/weapons.dmi
Labels: Feature, Ready for review, Sprites, Upstream Update

#494 [WIP] port oscar part 16, aka: OH GOD NONE OF THE FUCKING STAIRS WORK
  maps/CEVEris/Port_Oscar.dmm
Labels: Feature, Map Changes, Work in Progress

#495 Occultist Addition: First pass on weapon sprites
  zzzz_modular_occulus/icons/obj/occultist_weap/occcassad.dmi
  zzzz_modular_occulus/icons/obj/occultist_weap/occchain.dmi
  zzzz_modular_occulus/icons/obj/occultist_weap/occgun.dmi
  zzzz_modular_occulus/icons/obj/occultist_weap/occhammer.dmi
  zzzz_modular_occulus/icons/obj/occultist_weap/occsword.dmi
  zzzz_modular_occulus/icons/obj/occultist_weap/occultist.dmi
  zzzz_modular_occulus/icons/obj/occultist_weap/occvalk.dmi
  zzzz_modular_occulus/icons/obj/occultist_weap/projectiles.dmi
Labels: Changes Requested, Framework Addition

#491 Fixes captain voidsuit sprite
  cev_eris.dme
  zzzz_modular_occulus/code/modules/clothing/suit/suits.dm
Labels: Bugfix, Ready to Merge, Sprites

#496 port oscar part 17: THE STAIRS STILL DON'T FUCKING OWORK???
  maps/CEVEris/Port_Oscar.dmm
Labels: Map Changes, Priority: High, Ready to Merge

#498 Fixes the multieye bug, makes rejuv work properly
  code/datums/setup_option/core_implants.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Bugfix, Priority: High, Ready to Merge

#492 Occultist Additions: Powers (Part 1)
  cev_eris.dme
  zzzz_modular_occulus/code/game/antagonist/station/occultist.dm
  zzzz_modular_occulus/code/game/gamemodes/occultist/occultist_mind.dm
  zzzz_modular_occulus/code/game/gamemodes/occultist/occultist_powers.dm
  zzzz_modular_occulus/code/game/gamemodes/occultist/occultist_weapons.dm
Labels: Feature, Framework Addition, Ready to Merge
