Repository Occulus-Server/Occulus-Eris, pull requests merged in 2021-09, with the labels that each got.

#686 adds map for scales' event
  zzzz_modular_occulus/maps/eventmaps/churchevent/church_bear.dmm
  zzzz_modular_occulus/maps/occulus_areas.dm
Labels: [REDACTED], Map Changes

#689 fixes incendiary crate contents (plasma/phoron regression)
  code/modules/cargo/packs.dm
Labels: Bugfix, Ready to Merge

#690 Logging for the storyteller
  code/game/gamemodes/storyteller_print.dm
Labels: Administrative, Ready to Merge

#687 Stat caps, infections on examine, and empath perk
  code/__DEFINES/perks.dm
  code/datums/mob_stats.dm
  code/modules/mob/living/carbon/human/examine.dm
  zzzz_modular_occulus/code/datums/perks/oddity.dm
  zzzz_modular_occulus/code/game/gamemodes/occultist/occultist_mind.dm
  zzzz_modular_occulus/code/game/jobs/job/medical.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/examine.dm
Labels: Feature, Quality of Life, Ready for review, Balance/Rebalance

#685 unfuckles carpet crates
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/modules/cargo/packs.dm
Labels: Bugfix, Ready to Merge

#692 hotfix for ghost examines
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/examine.dm
Labels: Ready for review, Bugfix

#693 fixes power for port oscar museum, also modularizes an area change.
  code/game/area/asteroid_areas.dm
  zzzz_modular_occulus/maps/occulus_areas.dm
Labels: Modular, Bugfix, Map Changes

#699 port oscar beta part 1
  maps/CEVEris/Port_Oscar.dmm
Labels: Map Changes, Work in Progress

#691 Medical QoL improvements.
  cev_eris.dme
  zzzz_modular_occulus/code/game/objects/items/stacks/medical.dm
  zzzz_modular_occulus/code/modules/surgery/organic_damage.dm
Labels: Quality of Life, Balance/Rebalance, Ready to Merge

#696 Porting cigarette things from upstream that we missed
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/modules/reagents/reagent_containers/glass/beaker.dm
  icons/obj/cigarettes.dmi
Labels: Upstream Update, Sprites, Ready for review, Code Feature

#698 Corrects ADMS disk teleporation and feedback
  zzzz_modular_occulus/code/modules/maint_expeditions/ADMS.dm
Labels: Quality of Life, Bugfix, Ready to Merge

#688 Medbayadjustment2
  cev_eris.dme
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/window.dm
  icons/obj/Cryogenic2.dmi
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/machinery/smartfridge.dm
  zzzz_modular_occulus/code/game/objects/items/devices/perscriptionkit.dm
  zzzz_modular_occulus/code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  zzzz_modular_occulus/code/modules/reagents/reagents/pills.dm
  zzzz_modular_occulus/icons/obj/closet.dmi
  zzzz_modular_occulus/icons/obj/vending.dmi
  zzzz_modular_occulus/maps/areas.dm
Labels: Quality of Life, Needs Testing/Reproducing, Map Changes, Ready to Merge

#700 Disposals hotfix for new medbay
  maps/CEVEris/_CEV_Eris.dmm
Labels: Ready for review, Bugfix, Map Changes

#702 New Medbay Map Hotfix
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Ready to Merge

#703 Long Range Scanner and Trade Station fixes
  cev_eris.dme
  code/__DEFINES/trade.dm
  code/modules/long_range_scanner/long_range_scanner.dm
  code/modules/modular_computers/file_system/programs/generic/trade.dm
  code/modules/overmap/events/event.dm
  code/modules/trade/datums/trade_stations_presets/trash_refine.dm
  maps/CEVEris/centcomm.dmm
  zzzz_modular_occulus/code/game/objects/items/weapons/mine.dm
  zzzz_modular_occulus/code/modules/long_range_scanner/long_range_scanner.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/McRonalds.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/astertradecapital.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/boozefood.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/caduceus.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/fs_experimental_factory.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/fs_weapon_factory.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/hellcat.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/illegaltrader.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/mechas.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/mek_cruisers.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/serbianship.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/suit_up.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/tb_cheapammofactorys.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/zarya.dm
Labels: Feature, Quality of Life, Lore, Modular, Balance/Rebalance, Bugfix, Map Changes, Ready to Merge

#705 Yeetus NTeetus
  code/__DEFINES/machinery.dm
  code/__DEFINES/misc.dm
  code/controllers/subsystems/economy.dm
  code/controllers/subsystems/jobs.dm
  code/datums/setup_option/backgrounds/fate.dm
  code/datums/setup_option/backgrounds/origin.dm
  code/game/area/Space Station 13 areas.dm
  code/game/gamemodes/storytellers/erida.dm
  code/game/gamemodes/storytellers/guide.dm
  code/game/gamemodes/storytellers/healer.dm
  code/game/gamemodes/storytellers/mime.dm
  code/game/gamemodes/storytellers/sleeper.dm
  code/game/jobs/department.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
  code/game/jobs/job_controller.dm
  code/game/machinery/camera/camera_assembly.dm
  code/game/objects/items/devices/holowarrant.dm
  code/modules/holomap/holomap.dm
  code/modules/multiz/map_data.dm
  maps/CEVEris/datums/reports.dm
  maps/CEVEris/overmap-eris.dm
  maps/CEVEris/shuttles-eris.dm
  zzzz_modular_occulus/code/game/jobs/department.dm
  zzzz_modular_occulus/code/game/jobs/job/captain.dm
Labels: Lore, Lore Compliance, Ready to Merge

#701 port oscar beta part 2
  maps/CEVEris/Port_Oscar.dmm
Labels: Map Changes, Ready to Merge

#707 Medical supply balances
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/modules/economy/vending.dm
Labels: Balance/Rebalance, Map Changes, Ready to Merge

#709 QoL changes for EES SED, new sprites and lore
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/objects/items/devices/bosstown.dm
  zzzz_modular_occulus/icons/obj/device.dmi
Labels: Quality of Life, Sprites, Map Changes, Ready to Merge

#710 Fixes incorrect names on holomap legend
  code/modules/holomap/holomap_datum.dm
  zzzz_modular_occulus/icons/effects/64x64.dmi
Labels: Sprites, Lore Compliance, Ready to Merge

#711 VRRRRT-BWAAAAAHHHMP (Bluespace Jump Sound effects I mixmashed)
  code/controllers/evacuation/evacuation.dm
  zzzz_modular_occulus/sound/effects/bluespace_drive.ogg
  zzzz_modular_occulus/sound/effects/bluespace_drive_finish.ogg
  zzzz_modular_occulus/sound/effects/bluespace_drive_traveling.ogg
Labels: Feature, Ready to Merge, Audio

#715 Vendor Cleanup
  cev_eris.dme
  zzzz_modular_occulus/code/game/machinery/vending.dm
  zzzz_modular_occulus/code/modules/economy/vending.dm
Labels: Administrative, Ready to Merge, Code Cleanup

#716 Coin Minting and Premium Vendors 2: Capitalist Boogaloo
  cev_eris.dme
  code/game/machinery/vending.dm
  code/modules/mining/coins.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/datums/autolathe/coins.dm
  zzzz_modular_occulus/code/game/machinery/vending.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/_disks.dm
Labels: Feature, Balance/Rebalance, Ready to Merge

#717 New Single Action Revolver Sound Effects
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/revolver/saa.dm
  zzzz_modular_occulus/sound/weapons/guns/fire/saarevolverfire.ogg
Labels: Quality of Life, Ready for review, Audio

#720 Two minor lore fixes and makes the bomber jacket have some armor
  cev_eris.dme
  code/game/jobs/job/church.dm
  code/modules/modular_computers/file_system/programs/antagonist/uplink.dm
  zzzz_modular_occulus/code/modules/clothing/suit/suits.dm
Labels: Ready to Merge

#722 Never Fade Away: A Cruel and Tragic Story of Hair Gradients and Fades
  cev_eris.dme
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/external/organ_icon.dm
  code/modules/sprite_accessories/_accessory_markings.dm
  zzzz_modular_occulus/code/modules/sprite_accessories/_accesory_hair_fade.dm
  zzzz_modular_occulus/icons/mob/hair_fade.dmi
Labels: Feature, Sprites, Ready to Merge

#718 Armory and Argolyte maptweaks
  maps/CEVEris/_CEV_Eris.dmm
Labels: Quality of Life, Balance/Rebalance, Ready to Merge

#708 Deepflare disk
  cev_eris.dme
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/_disks.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/dss.dm
  zzzz_modular_occulus/code/modules/clothing/spacesuits/void/station.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/dssgemini.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/dssguns.dm
  zzzz_modular_occulus/code/modules/projectiles/projectile/bullettypes.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/astertradecapital.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/illegaltrader.dm
  zzzz_modular_occulus/code/modules/trade/datums/trade_stations_presets/suit_up.dm
  zzzz_modular_occulus/icons/inventory/head/icon.dmi
  zzzz_modular_occulus/icons/inventory/head/mob.dmi
  zzzz_modular_occulus/icons/inventory/suit/deepflare.dmi
  zzzz_modular_occulus/icons/inventory/suit/icon.dmi
  zzzz_modular_occulus/icons/inventory/suit/mob.dmi
  zzzz_modular_occulus/icons/obj/discs.dmi
  zzzz_modular_occulus/icons/obj/guns/energy/resolute.dmi
  zzzz_modular_occulus/icons/obj/guns/energy/stalwart.dmi
  zzzz_modular_occulus/icons/obj/guns/projectile.dmi
Labels: Feature, Ready to Merge

#725 Hotfix for noncompilage
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/dss.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/dssguns.dm
Labels: Priority: Critical, Ready to Merge
