Repository Occulus-Server/Occulus-Eris, pull requests merged in 2021-06, with the labels that each got.

#499 Equal Opportunity Sports Vestiments
  zzzz_modular_occulus/code/modules/clothing/under/jobs/civilian.dm
  zzzz_modular_occulus/icons/inventory/uniform/mob.dmi
  zzzz_modular_occulus/icons/inventory/uniform/mob_fem.dmi
Labels: Ready to Merge, Sprites

#497 port oscar part 18: fixes from playtest
  maps/CEVEris/Port_Oscar.dmm
Labels: Bugfix, Map Changes, Ready to Merge

#503 Fixes duplicate core implants and miscellaneous runtimes
  code/datums/setup_option/core_implants.dm
  code/modules/soulcrypt/base_implant.dm
Labels: Bugfix, Priority: High, Ready to Merge

#504 Rubberizes Rubber Bullets
  zzzz_modular_occulus/code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance/Rebalance, Bugfix, Ready to Merge

#506 Retail Scanner Icons replaced
  zzzz_modular_occulus/icons/obj/device.dmi
Labels: Ready to Merge, Sprites

#507 Fixes duplicate core implants without rebreaking everything
  code/datums/setup_option/core_implants.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Code Cleanup, Ready to Merge

#508 Deletes all roundstart monkeys, and more
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Ready to Merge

#509 Fixes the SC updater eating IDs, fixes holochip init
  code/modules/soulcrypt/access_update_tool.dm
  code/modules/soulcrypt/holochip.dm
Labels: Bugfix, Ready to Merge

#510 Revert "Fixes duplicate core implants without rebreaking everything"
  code/datums/setup_option/core_implants.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Revert

#512 Revert "Fixes the multieye bug, makes rejuv work properly"
  code/datums/setup_option/core_implants.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Revert

#515 Revert "Revert "Fixes the multieye bug, makes rejuv work properly""
  code/datums/setup_option/core_implants.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Revert

#517 Revert "Revert "Fixes duplicate core implants and miscellaneous runtimes""
  code/datums/setup_option/core_implants.dm
  code/modules/soulcrypt/base_implant.dm
Labels: Revert

#518 Revert "Revert "Fixes duplicate core implants without rebreaking everything""
  code/datums/setup_option/core_implants.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Revert

#513 The dme change that lets my PR work whoops
  cev_eris.dme
Labels: Feature, Ready to Merge

#516 New command stashes
  code/modules/stashes/stash_types/captain.dm
  zzzz_modular_occulus/code/modules/stashes/stashes.dm
Labels: Balance/Rebalance, Lore Compliance, Ready to Merge

#519 Handtele now works on all valid zlevels
  code/game/objects/items/weapons/teleportation.dm
Labels: Code Cleanup, Ready for review

#521 Re-enables client FPS settings
  code/modules/client/client procs.dm
  code/modules/client/preference_setup/global/01_ui.dm
Labels: Code Cleanup, Feature, Ready to Merge

#526 Changes Alert Levels Text
  code/datums/security_state.dm
  zzzz_modular_occulus/code/game/occulus-lore-fixes.dm
Labels: Lore Compliance, Ready to Merge

#527 Sets feet blood DNA to null upon cleaning.
  code/modules/mob/living/carbon/human/human.dm
Labels: Bugfix, Code Cleanup, Ready to Merge

#524 Ports gun dismantling
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/slaught_o_matic.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/revolver/sky_driver.dm
  code/modules/tips_and_tricks/gameplay.dm
Labels: Feature, Ready to Merge, Upstream Update

#520 [READY FOR REVIEW/MERGE] Tau Ceti Special, a revolver pistol.
  cev_eris.dme
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/shotgun/tauceti.dm
  zzzz_modular_occulus/icons/obj/guns/projectile/taucetispecial.dmi
Labels: Feature, Ready to Merge, Sprites

#525 Cleanup and Statweaks
  cev_eris.dme
  code/game/objects/structures/crates_lockers/crates.dm
  zzz_modular_syzygy/code/modules/reagents/recipes.dm
  zzz_modular_syzygy/icons/mob/back.dmi
  zzz_modular_syzygy/icons/mob/belt.dmi
  zzz_modular_syzygy/icons/mob/left_hand.dmi
  zzz_modular_syzygy/icons/mob/right_hand.dmi
  zzz_modular_syzygy/icons/mob/wielded.dmi
  zzz_modular_syzygy/icons/obj/ErisDefib.dmi
  zzzz_modular_occulus/__HELPERS/_helpers.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/_disks.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/ees.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/excelsior.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/mekhane.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/nanotrasen.dm
  zzzz_modular_occulus/code/modules/defib.dm
  zzzz_modular_occulus/code/modules/defiblocker.dm
  zzzz_modular_occulus/code/modules/organs/external/subtypes/robotic_types.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/plasma.dm
  zzzz_modular_occulus/code/modules/reagents/recipes.dm
  zzzz_modular_occulus/icons/eris_prosthesis/advanced_ghetto.dmi
  zzzz_modular_occulus/icons/eris_prosthesis/asters.dmi
  zzzz_modular_occulus/icons/eris_prosthesis/claw_arm.dmi
  zzzz_modular_occulus/icons/eris_prosthesis/excelsior.dmi
  zzzz_modular_occulus/icons/eris_prosthesis/frozen_star.dmi
  zzzz_modular_occulus/icons/eris_prosthesis/generic.dmi
  zzzz_modular_occulus/icons/eris_prosthesis/ghetto.dmi
  zzzz_modular_occulus/icons/eris_prosthesis/moebius.dmi
  zzzz_modular_occulus/icons/eris_prosthesis/neotheology.dmi
  zzzz_modular_occulus/icons/eris_prosthesis/one_star.dmi
  zzzz_modular_occulus/icons/eris_prosthesis/serbian.dmi
  zzzz_modular_occulus/icons/eris_prosthesis/spike_arm.dmi
  zzzz_modular_occulus/icons/eris_prosthesis/tank_leg.dmi
  zzzz_modular_occulus/icons/eris_prosthesis/technomancer.dmi
  zzzz_modular_occulus/icons/obj/ErisDefib.dmi
  zzzz_modular_occulus/prosthesis/prosthesis_parts.dm
Labels: Administrative, Balance/Rebalance, Bugfix, Quality of Life, Ready to Merge

#528 Extends GC hard delete warning time to 2 seconds
  code/controllers/subsystems/garbage.dm
Labels: Quality of Life, Ready to Merge

#522 Ensign Content Update Part 1
  cev_eris.dme
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/jobs/job/captain.dm
  zzzz_modular_occulus/code/game/objects/items/devices/radio.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/storage/pouches.dm
  zzzz_modular_occulus/code/game/objects/structures/crates_lockers/closets/secure/captain.dm
  zzzz_modular_occulus/code/modules/clothing/under/under.dm
  zzzz_modular_occulus/code/modules/loadout/lists/uniforms.dm
  zzzz_modular_occulus/icons/inventory/pockets/icon.dmi
  zzzz_modular_occulus/icons/inventory/uniform/ensign.dmi
  zzzz_modular_occulus/icons/inventory/uniform/mob.dmi
  zzzz_modular_occulus/icons/inventory/uniform/mob_fem.dmi
  zzzz_modular_occulus/icons/obj/closet.dmi
Labels: Code Cleanup, Feature, Map Changes, Ready to Merge, Sprites

#529 Marketable Lizard Plush
  code/modules/client/preference_setup/loadout/lists/misc.dm
  zzzz_modular_occulus/code/game/objects/items/plush.dm
  zzzz_modular_occulus/code/modules/stashes/stashes.dm
  zzzz_modular_occulus/icons/obj/plush.dmi
Labels: Feature, Ready to Merge, Sprites

#532 Adds missing file
  zzzz_modular_occulus/code/modules/research/xenoarchaeology/tools/anomaly_suit.dm
Labels: Bugfix, Modular, Ready for review

#533 Small Loadout Addition
  zzzz_modular_occulus/code/modules/loadout/lists/gloves.dm
  zzzz_modular_occulus/code/modules/loadout/lists/shoes.dm
Labels: Code Cleanup, Feature

#530 haha bluespace cat (port of #6138)
  code/game/machinery/mindswapper.dm
  code/modules/error_handler/error_handler.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  icons/mob/animal.dmi
Labels: Feature, Ready to Merge, Sprites

#531 A Surprisingly Painless Port of Erismed 3
  code/__DEFINES/damage_organs.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/global_lists.dm
  code/game/objects/items/weapons/implant/implants/carrion/infection_spider.dm
  code/modules/assembly/mousetrap.dm
  code/modules/client/preference_setup/augmentation/01_modifications.dm
  code/modules/core_implant/cruciform/rituals/inquisitor.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/dungeons/teleporter.dm
  code/modules/mechs/mech_damage.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  code/modules/mob/living/carbon/breathe.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/species_attack.dm
  code/modules/mob/living/carbon/human/species/station/slime.dm
  code/modules/mob/living/carbon/human/unarmed_attack.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/organs/blood.dm
  code/modules/organs/body_modifications.dm
  code/modules/organs/external/damage.dm
  code/modules/organs/external/dismemberment.dm
  code/modules/organs/internal/_internal.dm
  code/modules/organs/internal/blood_vessels.dm
  code/modules/organs/internal/carrion.dm
  code/modules/organs/internal/internal_organ_processes.dm
  code/modules/organs/internal/muscles.dm
  code/modules/organs/internal/nerves.dm
  code/modules/organs/organ_description.dm
  code/modules/organs/pain.dm
  code/modules/organs/surgery_helpers.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/toxins.dm
  zzzz_modular_occulus/code/modules/reagents/reagents/medicine.dm
Labels: Balance/Rebalance, Feature, Ready to Merge, Upstream Update

#534 Mek Electrohammer onmob sprites
  zzzz_modular_occulus/icons/obj/mek_melee.dmi
Labels: Ready to Merge, Sprites

#535 Blob Rebalance
  cev_eris.dme
  code/game/gamemodes/events/blob.dm
  code/modules/reagents/reagents/dispenser.dm
  zzzz_modular_occulus/code/game/gamemodes/events/blob.dm
  zzzz_modular_occulus/code/game/gamemodes/storytellers/storytellers.dm
Labels: Balance/Rebalance, Bugfix, Feature, Quality of Life, Ready to Merge

#536 Gives the Gunnery Sergeant a Jackhammer
  cev_eris.dme
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/shotgun/jackhammer.dm
  zzzz_modular_occulus/icons/obj/guns/projectile/jackhammer.dmi
Labels: Feature, Ready to Merge, Sprites

#537 Fixing undies, also cleans up character setup.
  cev_eris.dme
  code/modules/client/preference_setup/customization/01_ears.dm
  code/modules/client/preference_setup/matchmaking/matchmaking_disabled.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/client/preference_setup/preview.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bugfix, Code Cleanup, Feature, Quality of Life, Ready to Merge

#538 new underwear options
  code/datums/underwear/bottom.dm
  code/datums/underwear/socks.dm
  code/datums/underwear/top.dm
  code/datums/underwear/undershirt.dm
  icons/inventory/underwear/mob.dmi
Labels: Ready to Merge, Sprites

#539 Hotfix
  code/modules/mob/new_player/new_player.dm
Labels: Bugfix, Priority: Critical, Ready to Merge

#544 Testmerge to remove fluid pipes from the church
  maps/CEVEris/_CEV_Eris.dmm
Labels: Balance/Rebalance, Quality of Life, Ready for review

#543 Less cryptic admin messages for drone event
  code/game/gamemodes/events/rogue_drones.dm
Labels: Quality of Life, Ready to Merge

#542 nerfs oberth, adds to uplink at cheappo
  cev_eris.dme
  zzzz_modular_occulus/code/datums/uplink/highly visible and dangerous weapons.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/shotgun/tauceti.dm
Labels: Balance/Rebalance, Ready to Merge

#541 Experimental optimization of experimental optimizations
  code/modules/mob/living/life.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_powers.dm
Labels: Code Cleanup, Ready to Merge

#540 Attachable Skirts and Loadout tweaks
  cev_eris.dme
  zzzz_modular_occulus/code/modules/clothing/accessories/skirt.dm
  zzzz_modular_occulus/code/modules/clothing/under/under.dm
  zzzz_modular_occulus/code/modules/loadout/lists/accessories.dm
  zzzz_modular_occulus/code/modules/loadout/lists/uniforms.dm
  zzzz_modular_occulus/icons/inventory/accessory/skirt.dmi
  zzzz_modular_occulus/icons/inventory/accessory/skirtmob.dmi
Labels: Feature, Ready to Merge, Sprites

#546 Adds the ability to roll down jumpsuits
  cev_eris.dme
  code/modules/mob/living/carbon/human/update_icons.dm
  zzzz_modular_occulus/code/modules/clothing/clothing.dm
  zzzz_modular_occulus/icons/inventory/overlays.dmi
Labels: Feature, Quality of Life, Ready to Merge

#545 Centers Port Oscar.
  maps/CEVEris/Port_Oscar.dmm
Labels: Map Changes, Ready to Merge, Unreviewed Merge

#547 Fixes Stunglove electrocution
  zzzz_modular_occulus/code/modules/clothing/gloves/stungloves.dm
Labels: Bugfix, Ready to Merge

#551 Update poll_types.dm
  code/controllers/subsystems/voting/poll_types.dm
Labels: Balance/Rebalance, Ready to Merge

#548 port oscar part 20: a
  maps/CEVEris/Port_Oscar.dmm
Labels: Map Changes, Ready to Merge, Unreviewed Merge

#552 Fills in Techstorage
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Quality of Life, Ready to Merge

#553 Suit Sensor setting.
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/stripping.dm
Labels: Feature, Quality of Life, Ready to Merge

#555 Moves snack vendors into club, ups the amount of food per vendor, ups the cost of food, balances foods
  zzzz_modular_occulus/code/modules/economy/vending.dm
  zzzz_modular_occulus/code/modules/food/snacks.dm
Labels: Balance/Rebalance, Ready to Merge

#550 Tweaks to the Armory and Aegis roles
  code/game/jobs/job/security.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/jobs/job/security.dm
Labels: Balance/Rebalance, Map Changes, Modular, Ready to Merge

#554 A confused and ineffective rebalance of Erismed3 pain numbers
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/shock.dm
Labels: Balance/Rebalance, More Information Needed, Quality of Life, Ready for review

#557 Occultist Addition: Occultist weapon sprites and partial stats.
  cev_eris.dme
  code/__DEFINES/damage_organs.dm
  code/__DEFINES/items_clothing.dm
  code/game/antagonist/outer/mercenary/mercenary.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  zzzz_modular_occulus/code/game/gamemodes/occultist/occultist_weapons.dm
  zzzz_modular_occulus/icons/obj/occultist_weap/occchain.dmi
  zzzz_modular_occulus/icons/obj/occultist_weap/occgun.dmi
  zzzz_modular_occulus/icons/obj/occultist_weap/occhammer.dmi
  zzzz_modular_occulus/icons/obj/occultist_weap/occsword.dmi
Labels: Bugfix, Feature, Framework Addition, Ready to Merge

#559 Fixes adjusting clothing not updating the sprite
  zzzz_modular_occulus/code/modules/clothing/clothing.dm
Labels: Bugfix, Ready to Merge

#556 Elevator to the dorms!
  cev_eris.dme
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/gamemodes/events/weather/rad_storm.dm
  zzzz_modular_occulus/code/game/machinery/dorms_elevator.dm
  zzzz_modular_occulus/icons/obj/dorms_elevator.dmi
  zzzz_modular_occulus/sound/ambience/elevatormusic.ogg
  zzzz_modular_occulus/sound/effects/elevator_going_down.ogg
  zzzz_modular_occulus/sound/effects/elevator_going_up.ogg
Labels: Changes Requested, Feature, Modular

#562 Makes client FPS apply on connect
  code/modules/mob/login.dm
Labels: Bugfix, Ready for review

#564 Big Bluespace Harpoon Refactor
  code/game/objects/items/weapons/space_harpoon.dm
Labels: Bugfix, Code Cleanup, Quality of Life, Ready for review

#565 Ports JTB updates from upstream.
  cev_eris.dme
  code/__DEFINES/spawner/_spawner.dm
  code/game/objects/random/biomes/biomes.dm
  code/modules/dungeons/junk_tractor_beam.dm
  maps/submaps/junk_field/j25_25/ironhammer/ironhammer.dm
  maps/submaps/junk_field/j25_25/ironhammer/ironhammer1.dmm
  maps/submaps/junk_field/j25_25/ironhammer/ironhammer2.dmm
  maps/submaps/junk_field/j25_25/ironhammer/ironhammer3.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral.dm
  maps/submaps/junk_field/j25_25/neutral/neutral1.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral3.dmm
  maps/submaps/junk_field/j25_25/onestar/onestar.dm
  maps/submaps/junk_field/j25_25/onestar/onestar1.dmm
  maps/submaps/junk_field/j25_25/onestar/onestar2.dmm
  maps/submaps/junk_field/j25_25/onestar/onestar3.dmm
  maps/submaps/junk_field/j25_25/onestar/onestar4.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian.dm
  maps/submaps/junk_field/j25_25/serbian/serbian1.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian2.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian3.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral10.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral11.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral5.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral6.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral7.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral8.dmm
Labels: Code Cleanup, Feature, Ready for review, Upstream Update

#561 Core Implant Polishing Pass and Bonus Content
  code/modules/core_implant/cruciform/modules.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/soulcrypt/access_update_tool.dm
  code/modules/soulcrypt/base_implant.dm
  code/modules/soulcrypt/module.dm
  code/modules/soulcrypt/statpanel.dm
  zzzz_modular_occulus/code/modules/core_implant/cruciform/rituals/base.dm
  zzzz_modular_occulus/code/modules/soulcrypt/modules/tempperk.dm
  zzzz_modular_occulus/icons/obj/weapons.dmi
Labels: Bugfix, Code Cleanup, Feature, Ready to Merge, Sprites

#567 Fixed the ID and implants from dropping on the floor when leaving the round via the elevator.
  zzzz_modular_occulus/code/game/machinery/dorms_elevator.dm
Labels: Bugfix, Priority: High, Ready to Merge

#569 PANIC BANDAID: A desperate attempt to port unfinished, half-tested optimization code from upstream.
  code/__DEFINES/qdel.dm
  code/__HELPERS/global_lists.dm
  code/controllers/subsystems/garbage.dm
  code/controllers/subsystems/mapping.dm
  code/controllers/subsystems/processing/mobs.dm
  code/game/atoms_movable.dm
  code/game/objects/structures/burrows.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/maps/reader.dm
  code/modules/maps/swapmaps.dm
  code/modules/maps/tg/reader.dm
  code/modules/mechs/components/_components.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm
  code/modules/mob/living/carbon/superior_animal/roach/life.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/support.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_powers.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/simple_animal/borer/borer.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/multiz/map_data.dm
  code/modules/sanity/sanity_mob.dm
  code/modules/scrap/oldificator.dm
  code/world.dm
Labels: Code Cleanup, Ready for review, Upstream Update

#568 Fixes a runtime related to the SC access updater
  code/modules/soulcrypt/access_update_tool.dm
Labels: Bugfix, Ready to Merge

#570 Reduces requirement for crusades to 3 people, Adds a few more things to the Armory.
  code/modules/core_implant/cruciform/rituals/group.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Balance/Rebalance, Bugfix, Map Changes, Ready for review

#571 [WIP] Port part 21: junk beacon please work
  maps/CEVEris/Port_Oscar.dmm
Labels: Map Changes, Ready for review

#572 Captain Resprite Attempt Four
  cev_eris.dme
  zzzz_modular_occulus/code/datums/outfits/jobs/command.dm
  zzzz_modular_occulus/code/modules/clothing/gloves/captain.dm
  zzzz_modular_occulus/code/modules/clothing/head/head.dm
  zzzz_modular_occulus/code/modules/clothing/shoes/capshoes.dm
  zzzz_modular_occulus/code/modules/clothing/storage/backpack.dm
  zzzz_modular_occulus/code/modules/clothing/suit/suits.dm
  zzzz_modular_occulus/code/modules/clothing/under/under.dm
  zzzz_modular_occulus/icons/inventory/hands/gloves.dmi
  zzzz_modular_occulus/icons/inventory/head/icon.dmi
  zzzz_modular_occulus/icons/inventory/head/mob.dmi
  zzzz_modular_occulus/icons/inventory/shoes/captain.dmi
  zzzz_modular_occulus/icons/inventory/storage/backpack.dmi
  zzzz_modular_occulus/icons/inventory/suit/captain.dmi
  zzzz_modular_occulus/icons/inventory/uniform/captain.dmi
  zzzz_modular_occulus/icons/mob/gloves.dmi
  zzzz_modular_occulus/icons/mob/head.dmi
  zzzz_modular_occulus/icons/mob/left_hand.dmi
  zzzz_modular_occulus/icons/mob/right_hand.dmi
  zzzz_modular_occulus/icons/mob/shoes.dmi
  zzzz_modular_occulus/icons/mob/suit.dmi
  zzzz_modular_occulus/icons/mob/suit_fem.dmi
  zzzz_modular_occulus/icons/mob/uniform.dmi
  zzzz_modular_occulus/icons/mob/uniform_fem.dmi
  zzzz_modular_occulus/icons/obj/clothing/backpack.dmi
  zzzz_modular_occulus/icons/obj/clothing/suit.dmi
  zzzz_modular_occulus/icons/obj/clothing/uniforms.dmi
Labels: Feature, Ready for review, Sprites

#573 Carpet Redux
  cev_eris.dme
  code/datums/autolathe/biomatter.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/datums/autolathe/biomatter.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/_disks.dm
Labels: Feature

#576 nerfs secret notes
  zzzz_modular_occulus/code/game/objects/items/weapons/secrets.dm
Labels: Lore, Ready to Merge, [REDACTED]

#578 Removes JTB and the playable colony map. Emergency performance fix
  cev_eris.dme
  code/controllers/subsystems/misc.dm
  code/datums/autolathe/circuits.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/weapons/circuitboards/computer/computer.dm
  code/game/objects/random/biomes/biomes.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Bugfix, Priority: High, Ready for review, Removal

#581 Soulcrypt nutrition consumption reduced to a tenth
  code/modules/soulcrypt/base_implant.dm
Labels: Balance/Rebalance, Ready for review

#580 Doubles fannypack rarity
  zzzz_modular_occulus/code/game/objects/items/weapons/storage/pouches.dm
Labels: Balance/Rebalance, Ready for review

#577 Occultist Framework Addition: Call Swarm, Banish Swarm, Unearthly Wail
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/modules/projectiles/guns/mods/research_mods.dm
  zzzz_modular_occulus/code/game/gamemodes/occultist/occultist_mind.dm
  zzzz_modular_occulus/code/game/gamemodes/occultist/occultist_powers.dm
  zzzz_modular_occulus/code/game/gamemodes/occultist/occultist_weapons.dm
Labels: Bugfix, Feature, Framework Addition, Modular, Ready for review

#583 rope
  code/datums/underwear/undershirt.dm
  icons/inventory/underwear/mob.dmi
Labels: Ready for review, Sprites

#574 Ports the payday meme alongside the associated vendor
  code/datums/outfits/equipment/backpacks.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/obj/storage/backpack.dmi
  icons/obj/vending.dmi
  zzzz_modular_occulus/code/modules/economy/vending.dm
Labels: Map Changes, Ready to Merge, Sprites, Upstream Update
