Repository Occulus-Server/Occulus-Eris, pull requests merged in 2021-04, with the labels that each got.

#370 adds some solgov uniforms for the event tomorrow. Keeping the sprites for later!
  zzzz_modular_occulus/code/modules/clothing/head/head.dm
  zzzz_modular_occulus/code/modules/clothing/suit/suits.dm
  zzzz_modular_occulus/code/modules/clothing/under/under.dm
  zzzz_modular_occulus/icons/head_icons.dmi
  zzzz_modular_occulus/icons/inventory/head/solgovicon.dmi
  zzzz_modular_occulus/icons/inventory/head/solgovmob.dmi
  zzzz_modular_occulus/icons/inventory/suit/solgovicon.dmi
  zzzz_modular_occulus/icons/inventory/suit/solgovmob.dmi
  zzzz_modular_occulus/icons/inventory/uniform/solgovicon.dmi
  zzzz_modular_occulus/icons/inventory/uniform/solgovmob.dmi
  zzzz_modular_occulus/icons/inventory/uniform/solgovmobfem.dmi
  zzzz_modular_occulus/icons/mob/head.dmi
  zzzz_modular_occulus/icons/mob/suit.dmi
  zzzz_modular_occulus/icons/mob/suit_fem.dmi
  zzzz_modular_occulus/icons/mob/uniform.dmi
  zzzz_modular_occulus/icons/mob/uniform_fem.dmi
  zzzz_modular_occulus/icons/suit_icons.dmi
  zzzz_modular_occulus/icons/uniform_icons.dmi
Labels: Code Cleanup, Feature, Ready to Merge, Sprites

#366 Text "Volume" now respects selected font size.
  code/game/atoms.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/say.dm
  code/modules/organs/pain.dm
Labels: Bugfix, Ready to Merge

#367 Lore update and a map change
  code/game/objects/items/weapons/manuals.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzz_modular_syzygy/code/modules/loadout/lists/uniforms.dm
  zzzz_modular_occulus/code/game/occulus-lore-fixes.dm
Labels: Lore Compliance, Ready to Merge

#362 more Port Oscar stuff.
  maps/CEVEris/Port_Oscar.dmm
  zzzz_modular_occulus/code/game/objects/items/weapons/secrets.dm
Labels: Map Changes, Quality of Life, Work in Progress

#369 Detective's gear does not leave fibers
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/detectivework/forensics.dm
  zzzz_modular_occulus/code/game/jobs/job/security.dm
Labels: Bugfix, Quality of Life, Ready for review

#361 Hypospray rework 2.0
  code/modules/reagents/reagents/medicine.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/machinery/vending.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/storage/firstaid.dm
  zzzz_modular_occulus/code/modules/reagents/reagent_containers/hypospray.dm
  zzzz_modular_occulus/code/modules/reagents/reagent_containers/hypovial.dm
  zzzz_modular_occulus/code/modules/reagents/recipes.dm
  zzzz_modular_occulus/icons/obj/chemical.dmi
  zzzz_modular_occulus/icons/obj/reagentfillings.dmi
  zzzz_modular_occulus/icons/obj/reagentfillingsold.dmi
  zzzz_modular_occulus/icons/obj/syringe.dmi
Labels: Feature, Quality of Life, Ready to Merge, Sprites

#368 postmortum restorative patch
  cev_eris.dme
  code/modules/organs/external/_external.dm
  zzzz_modular_occulus/code/modules/reagents/reagents/medicine.dm
  zzzz_modular_occulus/code/modules/surgery/organic_damage.dm
Labels: Feature, Modular, Quality of Life, Ready to Merge

#373 Fixes mines
  zzzz_modular_occulus/code/game/objects/items/weapons/mine.dm
Labels: Balance/Rebalance, Bugfix, Ready to Merge

#365 Adds a number of new toolmods, weapons, and some new functionality
  cev_eris.dme
  code/__DEFINES/items.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/mekhane_armory.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/tools/mods/mod_types.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/dssgemini.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/mods/mods.dm
  zzzz_modular_occulus/icons/obj/guns/energy/gemini.dmi
  zzzz_modular_occulus/icons/obj/mek_melee.dmi
  zzzz_modular_occulus/icons/obj/tool_upgrades.dmi
Labels: Balance/Rebalance, Bugfix, Feature, Modular, Ready for review

#374 Added Solgov uniforms to loadouts
  cev_eris.dme
  zzz_modular_syzygy/code/modules/loadout/lists/uniforms.dm
  zzz_modular_syzygy/loadout.dm
  zzzz_modular_occulus/code/modules/clothing/head/head.dm
  zzzz_modular_occulus/code/modules/clothing/suit/suits.dm
  zzzz_modular_occulus/code/modules/clothing/under/under.dm
  zzzz_modular_occulus/code/modules/loadout/lists/eyegear.dm
  zzzz_modular_occulus/code/modules/loadout/lists/headwear.dm
  zzzz_modular_occulus/code/modules/loadout/lists/misc.dm
  zzzz_modular_occulus/code/modules/loadout/lists/suits.dm
  zzzz_modular_occulus/code/modules/loadout/lists/uniforms.dm
  zzzz_modular_occulus/icons/head_icons.dmi
  zzzz_modular_occulus/icons/inventory/head/icon.dmi
  zzzz_modular_occulus/icons/inventory/suit/captain.dmi
  zzzz_modular_occulus/icons/inventory/uniform/captain.dmi
  zzzz_modular_occulus/icons/inventory/uniform/yoga.dmi
  zzzz_modular_occulus/icons/uniform_icons.dmi
Labels: Feature, Modular, Ready for review

#386 fixes lag on returning to lobby
  code/controllers/subsystems/ticker.dm
Labels: Bugfix, Priority: High, Ready for review

#385 Fabkits, Carpets and some minor stuff
  cev_eris.dme
  code/datums/autolathe/biomatter.dm
  code/game/machinery/holoposter.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/structures/railing.dm
  code/modules/cargo/packs.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/datums/autolathe/fabkits.dm
  zzzz_modular_occulus/code/game/objects/items/fabkit.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/autolathe_disks.dm
  zzzz_modular_occulus/icons/obj/fabkits.dmi
Labels: Feature, Modular, Ready to Merge

#376 Buffing hivemind and blob spawn chance.
  zzzz_modular_occulus/code/game/gamemodes/storytellers/storyevent.dm
Labels: Balance/Rebalance, Ready to Merge

#380 hey who likes eris ports lol
  code/__DEFINES/is_helpers.dm
  code/game/machinery/kitchen/gibber.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
Labels: Balance/Rebalance, Quality of Life, Ready to Merge, Upstream Update

#381 Drug Side Effects
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/medicine.dm
  zzzz_modular_occulus/code/modules/reagents/reagents/medicine.dm
Labels: Balance/Rebalance, Ready to Merge

#377 EMP mines
  code/game/objects/explosion.dm
  code/game/objects/items/weapons/emp_mine.dm
  code/game/objects/items/weapons/mine.dm
Labels: Balance/Rebalance, Quality of Life, Ready for review

#387 Major nerf to shields
  code/__DEFINES/shields.dm
  code/game/gamemodes/events/meteors.dm
  code/modules/shield_generators/shield_generator.dm
Labels: Balance/Rebalance, Quality of Life, Ready to Merge

#390 Removed random engine setup scrap in Section 1
  maps/CEVEris/_CEV_Eris.dmm
Labels: Bugfix, Map Changes

#392 Jackal Sprites
  zzzz_modular_occulus/code/modules/sprite_accessories/_accessories_sprite.dm
  zzzz_modular_occulus/icons/mob/jamini-markings.dmi
  zzzz_modular_occulus/icons/mob/jamini-tails.dmi
Labels: Modular, Sprites

#388 Tweaked internal organ sizes
  zzzz_modular_occulus/code/modules/organs/internal/blood_vessels.dm
Labels: Balance/Rebalance, Ready for review

#394 more eris ports, my sanity is draining
  cev_eris.dme
  code/__DEFINES/spawner.dm
  code/datums/autolathe/ammo.dm
  code/datums/autolathe/guns.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/design_disks/frozen_star.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/ammo.dmi
  icons/obj/food.dmi
  icons/obj/guns/projectile/tk.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Ready for review, Sprites, Upstream Update

#396 Update mod_types.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/tools/mods/mod_types.dm
Labels: Bugfix, Quality of Life, Ready for review

#391 Combat Tweaks: Roaches, Rubbershot, Kaisers
  cev_eris.dme
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/projectiles/projectile/bullettypes.dm
  zzz_modular_syzygy/ammo.dm
  zzz_modular_syzygy/icons/ammo.dmi
  zzzz_modular_occulus/code/modules/projectiles/ammunition/bullets.dm
  zzzz_modular_occulus/code/modules/projectiles/ammunition/magazines.dm
  zzzz_modular_occulus/code/modules/projectiles/projectile/bullettypes.dm
  zzzz_modular_occulus/code/modules/tables/tables.dm
  zzzz_modular_occulus/icons/obj/ammo.dmi
Labels: Balance/Rebalance, Bugfix, Feature, Ready to Merge

#393 Magnetic door lock/braces port
  cev_eris.dme
  code/game/machinery/doors/airlock.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/__HELPERS/turfs.dm
  zzzz_modular_occulus/code/game/objects/items/devices/magnetic_lock.dm
  zzzz_modular_occulus/icons/obj/magnetic_locks.dmi
  zzzz_modular_occulus/icons/obj/magnetic_locks/centcom.dmi
  zzzz_modular_occulus/icons/obj/magnetic_locks/engineering.dmi
  zzzz_modular_occulus/icons/obj/magnetic_locks/security.dmi
Labels: Changes Requested, Feature, Pending Community Discussion/Vote

#406 eris ports but not bad this time
  cev_eris.dme
  code/ZAS/Airflow.dm
  code/__DEFINES/subsystems-priority.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/game.dm
  code/controllers/subsystems/tickets/mentor_tickets.dm
  code/controllers/subsystems/tickets/tickets.dm
  code/datums/topic/world.dm
  code/game/machinery/vending.dm
  code/game/objects/structures/low_wall.dm
  code/modules/admin/admin.dm
  code/modules/admin/tickets/adminticketsverbs.dm
  code/modules/admin/tickets/mentorticketsverbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/goonchat/browserassets/css/browserOutput_override.css
  code/modules/projectiles/guns/projectile/automatic/slaught_o_matic.dm
  code/modules/reagents/reagent_containers/glass/beaker.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/tables/tables.dm
  code/stylesheet.dm
  icons/obj/chemical.dmi
  icons/obj/guns/projectile/slaught_o_matic.dmi
  icons/obj/reagentfillings.dmi
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/pistol/ec9.dm
  zzzz_modular_occulus/code/modules/reagents/reagent_containers/hypovial.dm
Labels: Balance/Rebalance, DO NOT MERGE!!, Quality of Life, Ready to Merge

#410 Ports 5806 - 5821
  code/__DEFINES/mobs.dm
  code/__DEFINES/perks.dm
  code/game/antagonist/antagonist.dm
  code/game/antagonist/outer/mercenary/mercenary.dm
  code/game/machinery/cryopod.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/weapons/maneki_neko.dm
  code/game/objects/random/ammo.dm
  code/game/objects/random/spawner.dm
  code/modules/cargo/packs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/simple_animal/borer/borer_powers.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/reagents/enricher.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagents/other.dm
  icons/obj/christmas.dmi
Labels: Ready to Merge, Upstream Update

#401 fixes space suits not providing full hot, cold, and rad protection
  zzzz_modular_occulus/code/modules/clothing/spacesuits/void/station.dm
Labels: Bugfix, Modular

#403 Jamini pdafixes
  zzzz_modular_occulus/code/game/jobs/job/civilian.dm
  zzzz_modular_occulus/code/game/jobs/job/guild.dm
Labels: Balance/Rebalance, Modular, Quality of Life, Ready for review

#404 (Proof of concept) Minimum identification levels for reagents
  cev_eris.dme
  code/game/atoms.dm
  code/modules/reagents/reagents.dm
  zzzz_modular_occulus/code/modules/reagents/chemical_identification.dm
Labels: Balance/Rebalance, Feature, Quality of Life, Ready for review

#398 Jamini admincleanup
  cev_eris.dme
  zzz_modular_eclipse/readme.md
  zzz_modular_syzygy/code/game/objects/items/NZR.dm
  zzz_modular_syzygy/code/game/objects/items/tools/_tools.dm
  zzz_modular_syzygy/code/modules/loot_spawn_blacklist.dm
  zzz_modular_syzygy/code/modules/mining/mineral_effect.dm
  zzz_modular_syzygy/hugbox.dm
  zzz_modular_syzygy/icons/obj/sofas.dmi
  zzz_modular_syzygy/stashes.dm
  zzzz_modular_occulus/code/game/objects/effects/decals/cleanable/humans.dm
  zzzz_modular_occulus/code/game/objects/effects/decals/cleanable/misc_occulus.dm
  zzzz_modular_occulus/code/game/objects/items/translators.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/grenades/stinger.dm
  zzzz_modular_occulus/code/game/objects/structures/crates_lockers/closets/secure/captain.dm
  zzzz_modular_occulus/code/game/objects/structures/stool_bed_chair_nest/sofas.dm
  zzzz_modular_occulus/code/modules/cargo/packs.dm
  zzzz_modular_occulus/code/modules/economy/atm.dm
  zzzz_modular_occulus/code/modules/hivemind/core.dm
  zzzz_modular_occulus/code/modules/loot_spawn_blacklist.dm
  zzzz_modular_occulus/code/modules/materials/biomatter.dm
  zzzz_modular_occulus/code/modules/mining/mineral_effect.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/defense.dm
  zzzz_modular_occulus/code/modules/power/supermatter.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/automatic/vector.dm
  zzzz_modular_occulus/code/modules/stashes/stashes.dm
  zzzz_modular_occulus/icons/obj/guns/projectile/vector.dmi
  zzzz_modular_occulus/icons/obj/mining.dmi
  zzzz_modular_occulus/icons/obj/sofas.dmi
  zzzz_modular_occulus/icons/obj/stinger.dmi
  zzzz_modular_occulus/icons/obj/translators.dmi
  zzzz_modular_occulus/readme.md
Labels: Administrative

#411 Ports: [READY] Bluespace entropy (#5257)
  cev_eris.dme
  code/__HELPERS/bluespace_entropy.dm
  code/__HELPERS/turfs.dm
  code/datums/helper_datums/teleport.dm
  code/datums/uplink/uplink_items.dm
  code/game/machinery/excelsior/ex_teleporter.dm
  code/game/machinery/teleporter.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/space_harpoon.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/teleportation.dm
  code/game/objects/items/weapons/tools/knives.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/structures/beacon.dm
  code/game/objects/structures/bluespace_crystal_structure.dm
  code/game/objects/structures/omnius.dm
  code/modules/bs_snare/machinery.dm
  code/modules/clothing/spacesuits/rig/modules/ninja.dm
  code/modules/clothing/suits/armor.dm
  code/modules/dungeons/teleporter.dm
  code/modules/hivemind/self_defense.dm
  code/modules/hydroponics/seed.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm
  code/modules/mob/living/simple_animal/hostile/stranger.dm
  code/modules/telesci/bcrystal.dm
  code/modules/telesci/telepads.dm
  code/modules/telesci/telesci_computer.dm
  icons/mob/animal.dmi
  icons/mob/mob.dmi
  icons/mob/screen/gun_actions.dmi
  icons/obj/bluespace_crystal_structure.dmi
  icons/obj/guns/energy/lancer.dmi
Labels: Feature, Ready for review, Upstream Update

#412 Prosthetic repair standardization (#5823)
  code/game/machinery/vending.dm
  code/game/objects/items/stacks/nanopaste.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/modules/organs/wound.dm
  code/modules/power/cable.dm
  code/modules/research/designs.dm
  zzzz_modular_occulus/code/game/machinery/vending.dm
Labels: Upstream Update

#408 Port: Changes to cruciform energy regeneration and rituals. (#5975)
  code/__DEFINES/components.dm
  code/modules/core_implant/core_implant.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/crusader.dm
  code/modules/core_implant/cruciform/rituals/machinery.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/core_implant/group_ritual.dm
  code/modules/core_implant/ritual.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/say.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/drugs.dm
  nano/images/kneeling.png
  nano/templates/sanity.tmpl
  zzzz_modular_occulus/code/modules/core_implant/cruciform/cruciform.dm
Labels: Balance/Rebalance, Quality of Life, Ready for review, Upstream Update

#414 More ports ( 5848, 5847)
  cev_eris.dme
  code/datums/autolathe/biomatter.dm
  code/datums/contract.dm
  code/game/jobs/job/church.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/neotheology.dm
  zzzz_modular_occulus/code/game/jobs/job/church.dm
  zzzz_modular_occulus/code/modules/clothing/spacesuits/void/station.dm
  zzzz_modular_occulus/code/modules/clothing/suit/mekhane.dm
Labels: Ready for review, Upstream Update

#416 More ports: Vig impacts penetration, Bluespace entropy tweaks
  cev_eris.dme
  code/__HELPERS/bluespace_entropy.dm
  code/game/gamemodes/events/hidden_events/bluespace_crystal_infestation.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/teleportation.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm
  code/modules/mob/living/simple_animal/hostile/stranger.dm
  code/modules/projectiles/gun.dm
  code/modules/telesci/bcrystal.dm
  code/modules/trade/machinery/trade_beacon.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/dssgemini.dm
Labels: Bugfix, Feature, Ready for review, Upstream Update

#415 ports in Paris
  cev_eris.dme
  code/__DEFINES/perks.dm
  code/__DEFINES/weapons.dm
  code/datums/autolathe/guns.dm
  code/datums/perks/job.dm
  code/datums/perks/oddity.dm
  code/datums/uplink/announcements.dm
  code/datums/uplink/medical.dm
  code/datums/uplink/stealth and camouflage items.dm
  code/game/jobs/job/civilian.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/hacktool.dm
  code/game/objects/items/weapons/design_disks/autolathe_disks.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/clothing/head/armor.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/shrapnel.dm
  code/modules/projectiles/projectile/projectilegrenades.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagents/stims.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/obj/guns/energy/shrapnel.dmi
  sound/weapons/guns/fire/energy_shotgun.ogg
Labels: Balance/Rebalance, Bugfix, Feature, Ready for review

#402 Port oscar part 8
  maps/CEVEris/Port_Oscar.dmm
Labels: DO NOT MERGE!!, Map Changes

#417 fixed dme
  cev_eris.dme
Labels: Administrative, Bugfix, Ready for review

#419 EMP mine fixes, lore fixes
  cev_eris.dme
  code/__DEFINES/spawner.dm
  code/game/objects/items/weapons/design_disks/_disk.dm
  code/game/objects/items/weapons/design_disks/asters.dm
  code/game/objects/items/weapons/design_disks/moebius.dm
  code/game/objects/items/weapons/design_disks/one_star.dm
  code/game/objects/items/weapons/design_disks/technomancers.dm
  code/game/objects/items/weapons/emp_mine.dm
  code/game/objects/random/biomes/tech.dm
  code/game/objects/random/lathe_disks.dm
  code/game/objects/random/techparts.dm
  code/modules/scrap/scrap.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/_disks.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/cobalt.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/ees.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/generic.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/mekhane.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/nanotrasen.dm
Labels: Balance/Rebalance, Bugfix, Feature, Quality of Life, Ready for review

#423 Adds ensign quarters
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Quality of Life, Ready for review

#421 SUS AMOGUS PORTS!!!! IMPOSTER!!!!
  code/_onclick/item_attack.dm
  code/datums/autolathe/clothing.dm
  code/datums/contract.dm
  code/game/objects/items/weapons/design_disks/ironhammer.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/sword_of_truth.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/core_implant/cruciform/rituals/group.dm
  code/modules/organs/external/_external.dm
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Ready for review, Upstream Update

#420 Ports up through 5931
  cev_eris.dme
  code/__DEFINES/items.dm
  code/__DEFINES/projectile_defines.dm
  code/datums/autolathe/biomatter.dm
  code/datums/craft/recipes/weapon.dm
  code/datums/outfits/jobs/church.dm
  code/datums/perks/job.dm
  code/datums/uplink/highly visible and dangerous weapons.dm
  code/datums/uplink/neotheology.dm
  code/game/jobs/job/church.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/chameleonproj.dm
  code/game/objects/items/devices/organ_module/active/armblades.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/storage/sheath.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/items/weapons/tools/knives.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/items/weapons/tools/saws.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/items/weapons/tools/wrenches.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/neotheology.dm
  code/modules/hivemind/machines.dm
  code/modules/hivemind/mobs.dm
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/guns/mods/research_mods.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/stashes/stash_types/valueables.dm
  icons/obj/guns/mods.dmi
  icons/obj/sheath.dmi
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/_disks.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/mekhane.dm
  zzzz_modular_occulus/code/modules/clothing/spacesuits/rig/suits/combat.dm
  zzzz_modular_occulus/code/modules/loadout/lists/suits.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/egun.dm
Labels: Balance/Rebalance, Bugfix, Feature, Merge Conflict, Quality of Life, Ready to Merge, Upstream Update
