Repository Occulus-Server/Occulus-Eris, pull requests merged in 2021-01, with the labels that each got.

#108 Fixes a runtime and makes oddities have perks again!
  code/game/objects/items/oddities.dm
  code/modules/surgery/surgery_ui.dm
Labels: Bugfix, Priority: High, Ready to Merge

#115 Fixed nonhumans getting doubled organs on clone
  code/modules/mob/living/carbon/human/human.dm
Labels: Bugfix, Priority: High, Ready to Merge

#109 Quick rebalancing patch
  cev_eris.dme
  code/datums/outfits/jobs/civilian.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/autolathe_disks.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/pistol/ec9.dm
Labels: Balance/Rebalance, Modular, Quality of Life, Ready to Merge

#112 Maps in an underwear drawer, deletes extraneous bar chairs
  maps/CEVEris/_CEV_Eris.dmm
Labels: Bugfix, Map Changes, Ready to Merge

#113 A number of small bugfixes and tweaks
  cev_eris.dme
  code/modules/mob/living/carbon/human/examine.dm
  zzz_modular_syzygy/clothing.dm
  zzz_modular_syzygy/pouches.dm
  zzzz_modular_occulus/code/game/objects/random/utility.dm
  zzzz_modular_occulus/code/game/occulus-lore-fixes.dm
  zzzz_modular_occulus/code/modules/clothing/head/christmas.dm
  zzzz_modular_occulus/code/modules/clothing/head/head.dm
  zzzz_modular_occulus/code/modules/clothing/masks/masks.dm
  zzzz_modular_occulus/code/modules/clothing/suit/suits.dm
  zzzz_modular_occulus/code/modules/clothing/under/under.dm
Labels: Bugfix, Quality of Life, Ready to Merge

#114 Exercise Inspiration
  cev_eris.dme
  code/modules/sanity/sanity_mob.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/objects/items/toys/balls.dm
  zzzz_modular_occulus/code/game/objects/items/toys/costume.dm
  zzzz_modular_occulus/code/game/objects/items/toys/laserpointer.dm
  zzzz_modular_occulus/code/game/objects/structures/fitness.dm
  zzzz_modular_occulus/code/modules/sanity/sanity_mob.dm
  zzzz_modular_occulus/icons/mob/toys_l.dmi
  zzzz_modular_occulus/icons/mob/toys_mouth.dmi
  zzzz_modular_occulus/icons/mob/toys_r.dmi
  zzzz_modular_occulus/icons/obj/fitness.dmi
  zzzz_modular_occulus/icons/obj/toys.dmi
Labels: Feature, Quality of Life, Ready to Merge

#110 More cherrypicking, now starring: The Laurelin Bonsai, and shield generator fixes
  cev_eris.dme
  code/__DEFINES/perks.dm
  code/datums/objective/steal.dm
  code/datums/perks/oddity.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/jobs.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/techno_tribalism.dm
  code/game/objects/items/weapons/maneki_neko.dm
  code/modules/biomatter_manipulation/solidifier.dm
  code/modules/reagents/bonsai.dm
  code/modules/shield_generators/floor_diffuser.dm
  code/modules/shield_generators/hull.dm
  code/modules/shield_generators/shield.dm
  code/modules/shield_generators/shield_generator.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/modules/shield_generators/shield_generator.dm
Labels: Bugfix, Feature, Map Changes, Quality of Life, Ready for review, Upstream Update

#121 add new maint room(s) and also fix smol mapping error
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Ready to Merge

#122 Emergency eotp runtime fix
  code/modules/core_implant/cruciform/machinery/eotp.dm
Labels: Bugfix, Priority: Critical, Ready for review

#118 Reduces respawn delay to 10 minutes.
  code/controllers/configuration.dm
Labels: Quality of Life, Ready to Merge

#119 Suggbox Wave 1: Now with less CRLF crap
  cev_eris.dme
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Labels: Map Changes, Quality of Life, Ready to Merge

#120 The Big Soulcrypt Update
  cev_eris.dme
  code/datums/setup_option/core_implants.dm
  code/modules/soulcrypt/base_implant.dm
  code/modules/soulcrypt/holochip.dm
  code/modules/soulcrypt/module.dm
  code/modules/soulcrypt/statpanel.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/modules/soulcrypt/holochip.dm
  zzzz_modular_occulus/code/modules/soulcrypt/modules/language.dm
  zzzz_modular_occulus/code/modules/soulcrypt/modules/nanoui.dm
  zzzz_modular_occulus/code/modules/soulcrypt/modules/squawk.dm
  zzzz_modular_occulus/code/modules/soulcrypt/modules/statbooster.dm
  zzzz_modular_occulus/code/modules/soulcrypt/modules/tempperk.dm
Labels: Balance/Rebalance, Bugfix, Code Cleanup, Feature, Lore Compliance, Map Changes, Modular, Ready to Merge

#124 Adds a new oddity, an Isometric's Greatest Hits compilation.
  zzzz_modular_occulus/code/game/objects/items/oddities.dm
  zzzz_modular_occulus/icons/obj/oddities.dmi
Labels: Feature, Modular, Ready to Merge

#125 Bridge Officers
  code/__DEFINES/jobs.dm
  code/datums/outfits/jobs/civilian.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/jobs.dm
  code/modules/modular_computers/file_system/programs/generic/camera.dm
  code/modules/multiz/map_data.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/gamemodes/storytellers/storyevent.dm
  zzzz_modular_occulus/code/game/jobs/job/captain.dm
  zzzz_modular_occulus/code/game/jobs/job/civilian.dm
  zzzz_modular_occulus/code/game/jobs/job/engineering.dm
  zzzz_modular_occulus/code/game/jobs/job/medical.dm
  zzzz_modular_occulus/code/game/objects/structures/fitness.dm
Labels: Balance/Rebalance, Feature, Map Changes, Modular, Quality of Life, Ready to Merge

#129 Adds a new core deepmaint room, Chrome Labs
  cev_eris.dme
  zzzz_modular_occulus/maps/submaps/deepmaint_rooms/core/chromelab.dmm
  zzzz_modular_occulus/maps/submaps/deepmaint_rooms/core/core_rooms.dm
Labels: Map Changes, Modular, Ready to Merge

#126 oops all antags
  zzzz_modular_occulus/code/game/gamemodes/storytellers/storyevent.dm
Labels: Balance/Rebalance, Modular, Ready to Merge

#134 Events with a weighting of 0 will no longer fire.
  code/game/gamemodes/storyevent.dm
  code/game/gamemodes/storyteller.dm
Labels: Bugfix, Priority: High, Ready for review

#127 Soulcrypt Antispam Tweaks
  code/__DEFINES/soulcrypt.dm
  code/modules/soulcrypt/base_implant.dm
  code/modules/soulcrypt/statpanel.dm
Labels: Bugfix, Quality of Life, Ready for review

#128 Fixes Shorts
  zzz_modular_syzygy/code/modules/loadout/lists/uniforms.dm
Labels: Bugfix, Modular, Ready to Merge

#130 I Can't Believe It's The Perma Update!
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Ready to Merge

#139 Basis for hooded clothes
  cev_eris.dme
  zzzz_modular_occulus/code/modules/client/preference_setup/loadout/lists/suits.dm
  zzzz_modular_occulus/code/modules/clothing/head/hood.dm
  zzzz_modular_occulus/code/modules/clothing/suit/hooded.dm
  zzzz_modular_occulus/icons/inventory/head/hoods.dmi
  zzzz_modular_occulus/icons/inventory/suit/jacket.dmi
  zzzz_modular_occulus/icons/inventory/suit/jacketmob.dmi
Labels: Feature, Modular, Ready to Merge, Sprites

#117 Church Nerf Part 1
  cev_eris.dme
  code/modules/core_implant/cruciform/rituals/base.dm
  zzzz_modular_occulus/code/game/objects/items/oddities.dm
  zzzz_modular_occulus/code/modules/core_implant/cruciform/cruciform.dm
  zzzz_modular_occulus/code/modules/core_implant/cruciform/rituals/base.dm
  zzzz_modular_occulus/code/modules/core_implant/cruciform/rituals/priest.dm
Labels: Balance/Rebalance, Feature, Modular, Ready to Merge

#135 Re-rebalances the EC9
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/pistol/ec9.dm
Labels: Balance/Rebalance, Modular, Ready to Merge

#141 Bucket Transfer Change
  cev_eris.dme
  zzzz_modular_occulus/code/modules/reagents/reagent_containers/glass/beaker.dm
Labels: Modular, Quality of Life, Ready to Merge

#136 Unincludes bear's new dungeon from the main .dme
  cev_eris.dme
Labels: Code Cleanup, Ready to Merge

#138 *snap, *bark, and more!
  code/modules/mob/living/carbon/human/emote.dm
  zzzz_modular_occulus/sound/effects/fingersnap.ogg
  zzzz_modular_occulus/sound/voice/baa.ogg
  zzzz_modular_occulus/sound/voice/baa2.ogg
  zzzz_modular_occulus/sound/voice/bark2.ogg
  zzzz_modular_occulus/sound/voice/bork.ogg
  zzzz_modular_occulus/sound/voice/hiss.ogg
  zzzz_modular_occulus/sound/voice/mrow.ogg
  zzzz_modular_occulus/sound/voice/rattle.ogg
Labels: Feature, Ready to Merge

#140 Multiple minor maptweaks and vendor adjustments
  cev_eris.dme
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/modules/economy/price_list_fixed.dm
  zzzz_modular_occulus/code/modules/economy/vending.dm
Labels: Map Changes, Modular, Ready to Merge

#56 custom loadout names/descriptions
  cev_eris.dme
  code/modules/client/preference_setup/loadout/loadout.dm
  zzzz_modular_occulus/code/modules/client/preference_setup/loadout/gear_tweaks.dm
Labels: Feature, Ready for review

#143 Adding option to manually compile CL
  .github/workflows/compile_changelogs.yml
Labels: Administrative, Priority: High, Ready to Merge

#145 Update makechangelogs to acutally run on our Repo
  .github/workflows/make_changelogs.yml
Labels: Administrative, Priority: High, Ready to Merge

#144 Update compile_changelogs.yml
  .github/workflows/compile_changelogs.yml
Labels: Administrative, Priority: High, Ready to Merge

#146 Update make_changelogs.yml
  .github/workflows/make_changelogs.yml
Labels: Administrative, Priority: High, Ready for review

#147 Unbuggered The Cube Examine
  cev_eris.dme
  code/game/objects/items/devices/techno_tribalism.dm
Labels: Bugfix, Changes Requested

#149 Ports prosthetic/FBP limbs feeling pain, since we were talking about …
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/organs/pain.dm
  code/modules/scrap/scrap.dm
Labels: Balance/Rebalance, Ready to Merge, Upstream Update

#150 Cleanbot improvements (toggeable voice, more cleanables)
  code/modules/mob/living/bot/cleanbot.dm
Labels: Quality of Life, Ready to Merge

#151 Removes the vents and piping from chromelab deepmaint core
  zzzz_modular_occulus/maps/submaps/deepmaint_rooms/core/chromelab.dmm
Labels: Code Cleanup, Map Changes, Ready to Merge

#142 Revamps/remaps the space fortress into a One Star location.
  code/game/area/asteroid_areas.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  maps/encounters/spacefortress/spacefortress.dmm
Labels: Map Changes, Ready to Merge

#155 Fix RCON input load display
  code/modules/modular_computers/file_system/programs/engineering/rcon_console.dm
Labels: Bugfix, Ready to Merge

#154 Round End Credits
  cev_eris.dme
  code/_onclick/hud/fullscreen.dm
  code/controllers/subsystems/ticker.dm
  code/game/movietitles.dm
  code/modules/client/preference_setup/global/preferences.dm
Labels: Feature, Ready to Merge

#152 Update storytellers.dm
  zzzz_modular_occulus/code/game/gamemodes/storytellers/storytellers.dm
Labels: Balance/Rebalance, Modular, Quality of Life, Ready to Merge

#153 Makes rubbershot actually rubber
  zzzz_modular_occulus/code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance/Rebalance, Ready to Merge

#156 Adds a tcomms relay to the science shuttle
  cev_eris.dme
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/machinery/telecomms/presets.dm
Labels: Map Changes, Modular, Quality of Life, Ready to Merge

#157 Halves the nutrition cost of most litanies, and fixes some bugs
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/inquisitor.dm
  zzzz_modular_occulus/code/modules/core_implant/cruciform/rituals/base.dm
  zzzz_modular_occulus/code/modules/core_implant/cruciform/rituals/priest.dm
Labels: Balance/Rebalance, Quality of Life, Ready to Merge

#159 Fixes custom named item losing name when wielded
  code/game/objects/items/wielding.dm
Labels: Bugfix, Ready to Merge

#158 Adds a .40 lever action rifle
  cev_eris.dme
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/rifle/magnumlever.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/rifle/magnumleversawn.dm
  zzzz_modular_occulus/icons/obj/guns/projectile/magnumlever.dmi
  zzzz_modular_occulus/icons/obj/guns/projectile/magnumleversawn.dmi
Labels: Feature, Modular, Ready to Merge

#161 Fixes alt. title pay and display in crew manifest
  code/controllers/subsystems/jobs.dm
Labels: Bugfix, Ready to Merge

#162 Adds 'Union Salvage Technician' as an alt. title for Union Miner
  code/game/jobs/job/guild.dm
Labels: Feature, Ready to Merge

#163 Tunes up the Lever Action, clarifies it's caliber.
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/rifle/magnumlever.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/rifle/magnumleversawn.dm
Labels: Balance/Rebalance, Ready to Merge

#165 Cherypicks more hotkey stuff from upstream
  interface/skin.dmf
Labels: Quality of Life, Ready to Merge, Upstream Update

#166 Stop meteors from spawning pre-round and Runlevel fixes
  code/controllers/master.dm
  code/game/gamemodes/events/meteors.dm
Labels: Bugfix, Code Cleanup, Quality of Life, Ready to Merge

#167 Sleeveless Hoodie update: Black hoodie and female sprites!
  zzzz_modular_occulus/code/modules/client/preference_setup/loadout/lists/suits.dm
  zzzz_modular_occulus/code/modules/clothing/head/hood.dm
  zzzz_modular_occulus/code/modules/clothing/suit/hooded.dm
  zzzz_modular_occulus/icons/inventory/head/hoods.dmi
  zzzz_modular_occulus/icons/inventory/suit/jacket.dmi
  zzzz_modular_occulus/icons/inventory/suit/jacketmob.dmi
  zzzz_modular_occulus/icons/inventory/suit/jacketmob_fem.dmi
Labels: Feature, Modular, Ready to Merge, Sprites

#168 Adds and maps in the advanced roller bed!
  cev_eris.dme
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/objects/items/weapons/storage/belt.dm
  zzzz_modular_occulus/code/game/objects/structures/stool_bed_chair_nest/bed.dm
  zzzz_modular_occulus/icons/obj/rollerbed.dmi
Labels: Feature, Map Changes, Modular, Ready to Merge, Sprites

#169 Alt Civ Pack Balance Pass
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/automatic/rx8.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/pistol/ec9.dm
Labels: Balance/Rebalance, Modular, Ready to Merge

#175 Fix mech drills and improve feedback
  code/modules/mechs/equipment/utility.dm
Labels: Bugfix, Ready to Merge

#173 Makes body markings not lag anymore
  code/game/dna/dna2_helpers.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/external/organ_icon.dm
Labels: Code Cleanup, Priority: High, Ready to Merge

#177 Fix minerals so they can be seen through walls with mesons
  code/modules/mining/mineral_effect.dm
Labels: Bugfix, Ready to Merge

#179 Fixes to some nutrition costs
  code/modules/organs/internal/_internal.dm
  zzzz_modular_occulus/code/game/objects/structures/fitness.dm
Labels: Balance/Rebalance, Bugfix, Ready to Merge

#180 Jamini voidsuit prices
  zzzz_modular_occulus/code/modules/economy/price_list_fixed.dm
Labels: Balance/Rebalance, Modular, Quality of Life, Ready to Merge

#181 Revert "Makes body markings not lag anymore"
  code/game/dna/dna2_helpers.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/external/organ_icon.dm
Labels: Priority: Critical, Ready for review, Revert

#185 Revert "Revert "Makes body markings not lag anymore""
  code/game/dna/dna2_helpers.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/external/organ_icon.dm
Labels: Bugfix, Priority: High, Ready for review

#186 Stop pre-round meteors (without runlevel changes)
  code/game/gamemodes/events/meteors.dm
Labels: Bugfix, Ready to Merge

#187 Mining QoL Changes
  cev_eris.dme
  zzzz_modular_occulus/code/modules/mining/ore.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/inventory.dm
  zzzz_modular_occulus/code/modules/mob/living/silicon/robot/inventory.dm
Labels: Quality of Life, Ready to Merge

#192 Fix crafted drill heads
  code/modules/mechs/equipment/utility.dm
Labels: Bugfix, Ready to Merge
