Repository Occulus-Server/Occulus-Eris, pull requests merged in 2021-03, with the labels that each got.

#296 Adds internal Bleeding and other medical tweaks and nerfs
  cev_eris.dme
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/organs/external/_external.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/objects/items/weapons/autolathe_disks.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/species/station.dm
  zzzz_modular_occulus/code/modules/organs/internal/blood_vessels.dm
  zzzz_modular_occulus/code/modules/organs/organ.dm
Labels: Balance/Rebalance, Bugfix, Feature, Quality of Life, Ready to Merge

#303 Smelters no longer qdel mobs being processed inside of containers
  code/game/machinery/smelter.dm
Labels: Bugfix, Quality of Life, Ready to Merge

#302 Additional, non-lethal Carrion Spiderlings.
  cev_eris.dme
  zzzz_modular_occulus/code/game/gamemodes/changeling/modularchangeling.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/implant/implants/carrion/cleaner_spider.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/implant/implants/carrion/disruptor_spider.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/implant/implants/carrion/friend_spider.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/implant/implants/carrion/injector_spider.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/implant/implants/carrion/mending_spider.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/implant/implants/carrion/sleep_spider.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/implant/implants/carrion/smoker_spider.dm
  zzzz_modular_occulus/icons/obj/carrion_spiders.dmi
Labels: Feature, Modular, Ready to Merge

#293 Blitzshell Rework
  cev_eris.dme
  code/__DEFINES/gamemode.dm
  code/__HELPERS/antag.dm
  code/datums/ai_law_sets.dm
  code/datums/uplink/devices and tools.dm
  code/game/antagonist/antagonist_print.dm
  code/game/gamemodes/roleset/roleset.dm
  code/game/objects/items/devices/last_shelter.dm
  code/game/objects/items/weapons/circuitboards/machinery/chemistry.dm
  code/modules/mob/living/silicon/robot/drone/blitzshell.dm
  zzzz_modular_occulus/code/datums/objective/blitzshell.dm
  zzzz_modular_occulus/code/datums/uplink/devices and tools.dm
  zzzz_modular_occulus/code/game/antagonist/outer/blitzshell/blitzshell.dm
  zzzz_modular_occulus/code/game/gamemodes/storytellers/storyevent.dm
Labels: Feature, Ready to Merge, [REDACTED]

#308 Craftable Curtains
  cev_eris.dme
  zzzz_modular_occulus/code/datum/craft/recipes/furniture.dm
  zzzz_modular_occulus/code/game/objects/structures/curtains.dm
Labels: Feature, Modular, Ready to Merge

#304 Hypospray tweaks.
  zzzz_modular_occulus/code/modules/reagents/reagent_containers/hypospray.dm
Labels: Bugfix, Modular, Quality of Life, Ready to Merge

#305 Loads of small modifications and fixes
  cev_eris.dme
  code/game/movietitles.dm
  zzz_modular_syzygy/roach.dm
  zzz_modular_syzygy/vote.dm
  zzzz_modular_occulus/code/game/turfs/flooring/flooring_decals.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/rifle/levergun.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/rifle/magnumlever.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/rifle/magnumleversawn.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/rifle/sawnlevergun.dm
  zzzz_modular_occulus/icons/obj/guns/projectile/levergun.dmi
  zzzz_modular_occulus/icons/obj/guns/projectile/sawnlevergun.dmi
  zzzz_modular_occulus/icons/turf/flooring/decals.dmi
Labels: Bugfix, Lore Compliance, Quality of Life, Ready to Merge

#309 Fixes Roach Taming
  code/modules/mob/living/carbon/superior_animal/roach/attack.dm
  code/modules/mob/living/carbon/superior_animal/roach/riding.dm
Labels: Bugfix, Quality of Life, Ready to Merge

#310 Add check to prevent self-CPR
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Bugfix, Quality of Life, Ready to Merge

#311 New formula for self-surgery for more reliance on skills
  code/modules/surgery/surgery.dm
Labels: Balance/Rebalance, Ready to Merge

#314 Fixes mineral processors processing multiple alloys at once
  code/modules/mining/alloys.dm
  code/modules/mining/machine_processing.dm
Labels: Bugfix, Quality of Life, Ready to Merge

#316 Fixes blattedin reviving occuring when it should not
  code/modules/mob/living/carbon/superior_animal/roach/blattedin.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/superior_animal/roach/blattedin.dm
Labels: Bugfix, PR dependencies, Quality of Life, Ready to Merge

#317 Carrion spiders will not continaully try and jump on people
  code/game/objects/items/weapons/implant/implants/carrion/carrion_spiders.dm
Labels: Bugfix, Quality of Life, Ready to Merge

#315 Platinum now spawns in maint
  code/game/objects/structures/salvageable.dm
  code/modules/materials/material_sheets.dm
Labels: Quality of Life, Ready for review

#318 Compile fix. Speedmerge. From server filesy
  code/game/objects/structures/salvageable.dm
Labels: CI Failure, Priority: High

#320 Update hypospray.dm
  zzzz_modular_occulus/code/modules/reagents/reagent_containers/hypospray.dm
Labels: Balance/Rebalance, Bugfix, Quality of Life, Ready to Merge

#323 Insanity Devices Fix
  code/game/objects/items/devices/mind_fryer.dm
  code/game/objects/items/weapons/implant/implants/carrion/mindboil_spider.dm
  code/modules/projectiles/guns/energy/laser.dm
Labels: Bugfix, Quality of Life, Ready to Merge

#325 Other blattedin PR didn't merge right- Hecc
  code/modules/mob/living/carbon/superior_animal/roach/blattedin.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/superior_animal/roach/blattedin.dm
Labels: Bugfix, Quality of Life, Ready for review

#327 Adds a new Tail
  code/modules/sprite_accessories/sprite_accessories_vr.dm
  icons/mob/vore/tails_vr.dmi
Labels: Feature, Ready to Merge, Sprites

#326 Adds mind datum check to Insanity Devices
  code/game/objects/items/devices/mind_fryer.dm
  code/game/objects/items/weapons/implant/implants/carrion/mindboil_spider.dm
Labels: Bugfix, Quality of Life, Ready to Merge

#328 Changing Cruciform restrictions
  cev_eris.dme
  zzzz_modular_occulus/code/datums/setup_option/core_implants.dm
Labels: Balance/Rebalance, Lore Compliance, Quality of Life, Ready to Merge

#329 Various science, artist, and blacklist changes
  cev_eris.dme
  code/__HELPERS/artwork_names.dm
  code/controllers/subsystems/economy.dm
  code/game/machinery/autolathe/artist_bench.dm
  strings/artist_strings/names/art_creatures_names_plural.txt
  strings/artist_strings/names/art_objectsubject.txt
  strings/artist_strings/names/art_weapon_first.txt
  strings/artist_strings/names/art_weapon_second.txt
  zzzz_modular_occulus/code/modules/clothing/chameleon.dm
  zzzz_modular_occulus/code/modules/loot_spawn_blacklist.dm
  zzzz_modular_occulus/code/modules/research/nodes/engineering.dm
Labels: Balance/Rebalance, Bugfix, Lore Compliance, Quality of Life, Ready to Merge

#330 Aegis artifact now dispenses masterpiece donuts
  zzzz_modular_occulus/code/modules/game/Objects/Items/Devices/artifacts.dm
Labels: Modular, Quality of Life, Ready to Merge

#331 Pouch and belt storage nerf
  cev_eris.dme
  zzzz_modular_occulus/code/game/objects/items/weapons/mekhane_armory.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/storage/pouches.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/storage/storage.dm
Labels: Balance/Rebalance, Quality of Life, Ready to Merge

#333 Adjusted several traps
  cev_eris.dme
  code/game/objects/items/weapons/mine.dm
  code/game/objects/items/weapons/traps.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/mine.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/wire_splicing.dm
Labels: Balance/Rebalance, Bugfix, Feature, Modular, Ready to Merge

#334 Autodoc: Skip empty operations
  code/modules/surgery/autodoc.dm
Labels: Bugfix, Ready to Merge

#335 Allow .40 ammo to stack to 15 casings
  zzzz_modular_occulus/code/modules/projectiles/ammunition/bullets.dm
Labels: Bugfix, Modular, Ready to Merge

#336 Blacklist Excelsior machinegun and its magazine
  zzzz_modular_occulus/code/modules/loot_spawn_blacklist.dm
Labels: Modular, Ready to Merge

#337 Make superior animals (roaches, spiders) obey gravity
  code/modules/mob/living/carbon/superior_animal/life.dm
Labels: Bugfix, Quality of Life, Ready to Merge

#338 Hydro Tray tweaks
  cev_eris.dme
  zzzz_modular_occulus/code/modules/hydroponics/trays/tray_soil.dm
  zzzz_modular_occulus/code/modules/mining/ore.dm
  zzzz_modular_occulus/icons/obj/hydroponics_machines.dmi
Labels: Feature, Modular, Quality of Life, Ready to Merge

#340 Aegis and Cargo Maptweaks
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Quality of Life, Ready to Merge

#341 Teleport module nerf
  cev_eris.dme
  zzzz_modular_occulus/code/modules/clothing/spacesuits/rig/modules/ninja.dm
Labels: Balance/Rebalance, Ready to Merge

#342 Add two spriteless items to the blacklist
  zzzz_modular_occulus/code/modules/loot_spawn_blacklist.dm
Labels: Modular, Ready to Merge

#343 Fixes the fuel unit stuff on PACMANs being undefined
  nano/templates/pacman.tmpl
Labels: Bugfix, Ready to Merge

#344 Adds the nanite reconstitution apparatus (de-oldifier)
  cev_eris.dme
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/research/nodes/engineering.dm
  code/modules/scrap/oldificator.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/datums/autolathe/circuits.dm
  zzzz_modular_occulus/code/game/machinery/nanite_reconstitution_apparatus.dm
  zzzz_modular_occulus/icons/obj/machine.dmi
  zzzz_modular_occulus/nano/templates/nanite_reconstitution_apparatus.tmpl
  zzzz_modular_occulus/nano/templates/nanite_reconstitution_apparatus_materials.tmpl
  zzzz_modular_occulus/nano/templates/nanite_reconstitution_apparatus_reagents.tmpl
Labels: Feature, Map Changes, Modular, Ready to Merge

#345 fixed two up pipes that should be trunks
  maps/CEVEris/_CEV_Eris.dmm
Labels: Bugfix, Map Changes, Ready to Merge

#346 Merge Club Worker and Actor
  code/__DEFINES/jobs.dm
  code/game/jobs/job/civilian.dm
  zzzz_modular_occulus/code/game/jobs/job/civilian.dm
Labels: Feature, Modular, Ready to Merge

#347 Add roboticist alt. titles
  zzzz_modular_occulus/code/game/jobs/job/science.dm
Labels: Feature, Modular, Ready to Merge

#348 Announce alt. titles when joining the round
  code/controllers/subsystems/jobs.dm
  code/defines/procs/announce.dm
Labels: Feature, Ready to Merge

#349 Touch-ups to the Fight Club:tm:
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Quality of Life, Ready to Merge

#350 Update human_attackhand.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Balance/Rebalance, Quality of Life, Ready to Merge

#354 Removes DNA Switch Anomaly
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_dnaswitch.dm
Labels: Feature, Quality of Life, Ready to Merge

#356 Heavily rebalanced several voidsuit armor values. Mostly lower
  cev_eris.dme
  zzzz_modular_occulus/code/modules/clothing/spacesuits/void/station.dm
Labels: Balance/Rebalance, Quality of Life, Ready to Merge

#357 rebalanced serveral origins
  cev_eris.dme
  zzzz_modular_occulus/code/datums/setup_option/backgrounds/origin.dm
Labels: Balance/Rebalance, Modular, Quality of Life, Ready to Merge

#352 Implement emojicracy: Join silently as vagabond/in dormitories
  code/defines/procs/announce.dm
  code/modules/client/preference_setup/global/preferences.dm
Labels: Feature, Ready for review

#353 Cleanbot lagfix & associated changes
  zzzz_modular_occulus/code/modules/mob/living/bot/cleanbot_occulus.dm
Labels: Bugfix, Priority: High, Ready for review

#358 Rebalances Longsword
  cev_eris.dme
  zzzz_modular_occulus/code/game/objects/items/weapons/nt_melee.dm
Labels: Balance/Rebalance, Changes Requested, Quality of Life
