Repository Occulus-Server/Occulus-Eris, pull requests merged in 2021-10, with the labels that each got.

#729 Fixed missing line in the template file.
  nano/templates/lrscanner.tmpl
Labels: Bugfix, Ready to Merge

#733 Practice Mags Disk
  cev_eris.dme
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/frozen_star.dm
Labels: Feature, Quality of Life, Ready to Merge

#735 Deployable Bastion shield [Ready for Review]
  cev_eris.dme
  zzzz_modular_occulus/code/game/objects/items/weapons/shields.dm
  zzzz_modular_occulus/code/modules/research/designs.dm
  zzzz_modular_occulus/code/modules/research/nodes/combat.dm
  zzzz_modular_occulus/icons/obj/bastion.dmi
Labels: Feature, Ready to Merge

#742 Implements Custom Blood Colors
  code/modules/client/preference_setup/customization/01_ears.dm
  zzzz_modular_occulus/code/modules/client/preferences.dm
Labels: Feature, Ready for review

#744 Top Sneaky Event PR
  cev_eris.dme
  zzzz_modular_occulus/code/game/gamemodes/events/siren_scan.dm
  zzzz_modular_occulus/code/game/gamemodes/events/weather/siren_scan.dm
  zzzz_modular_occulus/code/game/turfs/flooring/flooring.dm
  zzzz_modular_occulus/code/game/turfs/flooring/flooring_decals.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/augmentor.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/composer.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/conservator.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/replicant.dm
  zzzz_modular_occulus/code/modules/projectiles/projectile/projectile.dm
  zzzz_modular_occulus/icons/mob/siren/augmentor.dmi
  zzzz_modular_occulus/icons/mob/siren/composer.dmi
  zzzz_modular_occulus/icons/mob/siren/conservator.dmi
  zzzz_modular_occulus/icons/mob/siren/replicant.dmi
  zzzz_modular_occulus/icons/turf/flooring/plating.dmi
  zzzz_modular_occulus/maps/eventmaps/siren/Final Frontierclean.dmm
  zzzz_modular_occulus/maps/eventmaps/siren/FinalFrontier.dm
  zzzz_modular_occulus/maps/eventmaps/siren/FinalFrontier.dmm
  zzzz_modular_occulus/maps/occulus_areas.dm
  zzzz_modular_occulus/sound/ambience/scaryambience.ogg
  zzzz_modular_occulus/sound/effects/The_Siren.wav
  zzzz_modular_occulus/sound/effects/screech.wav
  zzzz_modular_occulus/sound/effects/solonely.wav
  zzzz_modular_occulus/sound/effects/whispers.wav
  zzzz_modular_occulus/sound/voice/replicanthum.wav
  zzzz_modular_occulus/sound/voice/roboticactivation.wav
Labels: Sprites, Ready for review, Code Feature, Audio
