Repository Occulus-Server/Occulus-Eris, pull requests merged in 2021-08, with the labels that each got.

#620 portoscarpart26lmfao
  maps/CEVEris/Port_Oscar.dmm
Labels: Map Changes, Ready to Merge

#619 Elevator bug fixes!
  zzzz_modular_occulus/code/game/machinery/dorms_elevator.dm
Labels: Bugfix, Code Cleanup, Code Feature, Quality of Life, Ready for review

#606 Tweaks to the dorms and showers, and a few small fixes too small for their own PR
  code/modules/surgery/internal.dm
  icons/mob/vore/ears_vr.dmi
  icons/mob/vore/tails_vr.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Quality of Life, Ready to Merge

#621 halves Occultist power costs
  zzzz_modular_occulus/code/game/gamemodes/occultist/occultist_powers.dm
Labels: Balance/Rebalance, Quality of Life, Ready for review

#624 Catalyzer(catalyser?) Craftable Guns
  cev_eris.dme
  zzzz_modular_occulus/code/datum/craft/recipes/guns.dm
  zzzz_modular_occulus/code/game/objects/items/catacraft.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/corsair.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/didact.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/enforcer.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/sentinel.dm
  zzzz_modular_occulus/icons/obj/catacraft.dmi
  zzzz_modular_occulus/icons/obj/guns/energy/corsair.dmi
  zzzz_modular_occulus/icons/obj/guns/energy/didact.dmi
  zzzz_modular_occulus/icons/obj/guns/energy/enforcer.dmi
  zzzz_modular_occulus/icons/obj/guns/energy/sentinel.dmi
Labels: Feature, Modular, Ready to Merge

#623 red shemaugh
  zzzz_modular_occulus/code/modules/clothing/masks/masks.dm
  zzzz_modular_occulus/icons/inventory/mask/icon.dmi
  zzzz_modular_occulus/icons/inventory/mask/mob.dmi
Labels: Ready to Merge, Sprites

#625 Flavor Code Expansion
  cev_eris.dme
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_controller.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/reagents/reagent_containers/food/sandwich.dm
  zzzz_modular_occulus/code/modules/cooking/salad.dm
  zzzz_modular_occulus/code/modules/cooking/seed.dm
  zzzz_modular_occulus/code/modules/cooking/snacks.dm
  zzzz_modular_occulus/code/modules/food/snacks.dm
  zzzz_modular_occulus/icons/obj/food.dmi
Labels: Feature, Quality of Life, Ready to Merge

#629 Fixes makeshift AK not appearing in gun crafting.
  code/datums/craft/recipes/guns.dm
  code/datums/craft/recipes/misc.dm
Labels: Feature, Ready to Merge

#628 nerfs the cube.
  code/game/objects/items/devices/techno_tribalism.dm
Labels: Balance/Rebalance, Ready to Merge

#630 Fixes event refund code
  code/game/gamemodes/roleset/roleset.dm
Labels: Priority: High, Bugfix, Ready to Merge

#626 fixes dorm spawns
  code/modules/client/preferences_spawnpoints.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/machinery/dorms_elevator.dm
Labels: Quality of Life, Bugfix, Ready to Merge

#632 re-adds the virgo cat ears that don't sit properly on the sprite
  zzzz_modular_occulus/code/modules/sprite_accessories/_accessories_sprite.dm
  zzzz_modular_occulus/icons/mob/jamini-ears.dmi
Labels: Feature, Ready to Merge

#633 Summer update!
  cev_eris.dme
  icons/obj/drinks.dmi
  icons/obj/hydroponics_growing.dmi
  icons/obj/hydroponics_products.dmi
  icons/obj/seeds.dmi
  zzzz_modular_occulus/code/game/machinery/vending.dm
  zzzz_modular_occulus/code/modules/cooking/seed.dm
  zzzz_modular_occulus/code/modules/hydroponics/seed_datums.dm
  zzzz_modular_occulus/code/modules/hydroponics/seed_packets.dm
  zzzz_modular_occulus/code/modules/reagents/reagents/food-Drinks.dm
  zzzz_modular_occulus/code/modules/reagents/recipes.dm
Labels: Feature, Sprites, Modular, Ready to Merge

#635 Adds the White Nail rifle to R&D
  cev_eris.dme
  nano/css/shared.css
  nano/images/science.png
  zzzz_modular_occulus/code/modules/projectiles/ammunition/bullets.dm
  zzzz_modular_occulus/code/modules/projectiles/ammunition/magazines.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/rifle/whitenail.dm
  zzzz_modular_occulus/code/modules/projectiles/projectile/bullettypes.dm
  zzzz_modular_occulus/code/modules/research/designs.dm
  zzzz_modular_occulus/code/modules/research/nodes/combat.dm
  zzzz_modular_occulus/icons/obj/ammo.dmi
  zzzz_modular_occulus/icons/obj/guns/projectile/whitenail.dmi
  zzzz_modular_occulus/icons/obj/magazines.dmi
  zzzz_modular_occulus/sound/weapons/guns/fire/nail_fire.ogg
  zzzz_modular_occulus/sound/weapons/guns/interact/nail_in.ogg
  zzzz_modular_occulus/sound/weapons/guns/interact/nail_out.ogg
  zzzz_modular_occulus/sound/weapons/guns/misc/nail_refill.ogg
Labels: Feature, Sprites, Ready to Merge, Audio

#638 [WIP] changes wieldnoise on some guns
  cev_eris.dme
  zzzz_modular_occulus/code/modules/gunwieldingnoises.dm
  zzzz_modular_occulus/sound/weapons/guns/misc/wieldingnoises/aegis_rifle.ogg
  zzzz_modular_occulus/sound/weapons/guns/misc/wieldingnoises/ak47_manufactured.ogg
  zzzz_modular_occulus/sound/weapons/guns/misc/wieldingnoises/generic_gun.ogg
  zzzz_modular_occulus/sound/weapons/guns/misc/wieldingnoises/generic_pistol.ogg
  zzzz_modular_occulus/sound/weapons/guns/misc/wieldingnoises/novakovic_wield_clean.ogg
Labels: Feature, Ready to Merge

#640 Fixes wielding non-compile, added noise for Sol carbine and White Nail upon request.
  zzzz_modular_occulus/code/modules/gunwieldingnoises.dm
  zzzz_modular_occulus/sound/weapons/guns/misc/wieldingnoises/carbine_wield.ogg
  zzzz_modular_occulus/sound/weapons/guns/misc/wieldingnoises/nail_wield.ogg
Labels: Feature, Ready for review, Bugfix

#639 Fixes White Nail Sprite Bug
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/rifle/whitenail.dm
Labels: Bugfix, Ready to Merge

#637 Adds Two new tools, tweaks surgery, and adjusts putting tools on tables
  cev_eris.dme
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/shields.dm
  code/modules/cargo/packs.dm
  code/modules/mob/living/bot/secbot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
  code/modules/surgery/surgery.dm
  code/modules/tables/tables.dm
  code/modules/trade/datums/trade_stations_presets/hellcat.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/objects/items/tools/_tools.dm
  zzzz_modular_occulus/code/game/objects/items/tools/batons.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/ees.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/storage/pouches.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/tools/surgery.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/tools/weldingtool.dm
  zzzz_modular_occulus/code/modules/research/designs.dm
  zzzz_modular_occulus/code/modules/research/nodes/biotech.dm
  zzzz_modular_occulus/code/modules/research/nodes/engineering.dm
  zzzz_modular_occulus/icons/obj/_tools.dmi
Labels: Feature, Quality of Life, Balance/Rebalance, Ready to Merge

#641 Fixes orphaned Sending Trade Beacon circuit board.
  cev_eris.dme
  code/modules/trade/machinery/circuits/trade_beacon.dm
  zzzz_modular_occulus/code/modules/trade/machinery/circuits/trade_beacon.dm
Labels: Bugfix, Ready to Merge

#642 Instructional Manuals
  cev_eris.dme
  maps/CEVEris/Port_Oscar.dmm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/_DEFINES/spawner/_spawner.dm
  zzzz_modular_occulus/code/game/objects/items/instructional.dm
  zzzz_modular_occulus/code/game/objects/random/spawner_instructional.dm
  zzzz_modular_occulus/code/modules/sanity/sanity_mob.dm
  zzzz_modular_occulus/icons/obj/oddities.dmi
  zzzz_modular_occulus/icons/obj/spawners/instructional.dmi
Labels: Feature, Ready for review, Map Changes

#501 Newchems additions!
  cev_eris.dme
  code/modules/reagents/machinery/chem_dispenser.dm
  zzzz_modular_occulus/code/game/machinery/vending.dm
  zzzz_modular_occulus/code/modules/admin/verbs/sdql_2/sdql_2_std.dm
  zzzz_modular_occulus/code/modules/hydroponics/seed_datums.dm
  zzzz_modular_occulus/code/modules/hydroponics/seed_packets.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  zzzz_modular_occulus/code/modules/reagents/food-Drinks.dm
  zzzz_modular_occulus/code/modules/reagents/reagentprocs.dm
  zzzz_modular_occulus/code/modules/reagents/reagents/other.dm
  zzzz_modular_occulus/code/modules/reagents/reagents/toxins.dm
  zzzz_modular_occulus/code/modules/reagents/recipes.dm
  zzzz_modular_occulus/code/modules/telesci/bcrystal.dm
Labels: Feature, Modular, Ready to Merge

#643 fixes runtimes
  zzzz_modular_occulus/code/game/objects/items/instructional.dm
  zzzz_modular_occulus/code/game/objects/random/spawner_instructional.dm
  zzzz_modular_occulus/code/modules/reagents/recipes.dm
Labels: Ready for review, Bugfix

#644 Update blattedin.dm
  code/modules/mob/living/carbon/superior_animal/roach/blattedin.dm
Labels: Bugfix, Ready to Merge

#648 Removes the non-Mekhane biogenerator for lore and gameplay reasons
  code/game/machinery/biogenerator.dm
  code/game/objects/items/weapons/circuitboards/machinery/biogenerator.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/nodes/biotech.dm
Labels: Lore Compliance, Ready to Merge

#646 Makes the last shelter work
  code/game/objects/items/devices/last_shelter.dm
Labels: Ready to Merge, Code Feature

#649 Tweaks some gun stats, reworks the Svallin to a plasma pistol
  cev_eris.dme
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/mekhane.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/plasma.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/mods/mods.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/automatic/atreides.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/automatic/molly.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/automatic/straylight.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/automatic/vector.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/automatic/wintermute.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/pistol/handmade.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/shotgun/jackhammer.dm
Labels: Modular, Balance/Rebalance, Ready to Merge

#650 Last Shelter Prompt typo fix
  code/game/objects/items/devices/last_shelter.dm
Labels: Quality of Life, Ready for review, Ready to Merge

#651 Maint loot tweaks
  maps/CEVEris/_CEV_Eris.dmm
Labels: [REDACTED], Map Changes

#656 Update shovel.dm
  code/game/objects/items/weapons/tools/shovel.dm
Labels: [REDACTED], Balance/Rebalance

#658 Disables the wormhole event
  code/game/gamemodes/events/wormholes.dm
Labels: Ready for review, Bugfix

#645 Adds selectable pronouns to character creation, gender rework
  cev_eris.dme
  code/datums/contract.dm
  code/game/dna/side_effects.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/modular_computers/file_system/reports/crew_record.dm
  code/modules/sanity/breakdowns.dm
  zzzz_modular_occulus/__HELPERS/sorting/__main.dm
  zzzz_modular_occulus/code/datums/datacore.dm
  zzzz_modular_occulus/code/game/machinery/computer/medical.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/cards_ids.dm
  zzzz_modular_occulus/code/modules/client/preference_setup/loadout/01_basic.dm
  zzzz_modular_occulus/code/modules/client/preference_setup/loadout/02_body.dm
  zzzz_modular_occulus/code/modules/client/preferences.dm
  zzzz_modular_occulus/code/modules/mob/gender.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/examine.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/human_helpers.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/species/species.dm
  zzzz_modular_occulus/code/modules/mob/living/new_player/new_player.dm
  zzzz_modular_occulus/code/modules/mob/living/new_player/preferences_setup.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/friendly/corgi.dm
  zzzz_modular_occulus/code/modules/nano/modules/human_appearance.dm
  zzzz_modular_occulus/code/modules/reagents/reagents/stims.dm
  zzzz_modular_occulus/nano/templates/appearance_changer.tmpl
Labels: Feature, Ready to Merge

#665 Fixes Energy Armblade Augmentor
  zzzz_modular_occulus/code/game/objects/items/weapons/augmentor.dm
Labels: Bugfix, Ready to Merge

#622 Mob Agony Coefficients, new mobs, and the EES SED
  cev_eris.dme
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/objects/items/devices/bosstown.dm
  zzzz_modular_occulus/code/game/objects/random/mob.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/defense.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/nanoblob.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/roombattler.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/spud.dm
  zzzz_modular_occulus/icons/mob/roombattler.dmi
  zzzz_modular_occulus/icons/mob/spud.dmi
  zzzz_modular_occulus/icons/obj/device.dmi
Labels: Feature, Sprites, Balance/Rebalance, Map Changes, Ready to Merge

#661 Adds a teleporter and fixes a floor tile in the Space Ruins
  maps/encounters/spaceruins/spaceruins.dmm
Labels: Ready for review, Map Changes

#662 Fixes bring able to rip holes through the ship.
  cev_eris.dme
  code/__DEFINES/turfs.dm
  zzzz_modular_occulus/code/controllers/subsystems/staverbs.dm
  zzzz_modular_occulus/code/game/turfs/flooring/flooring.dm
Labels: Bugfix, Ready to Merge

#663 miscellanious map changes along with some fixes!
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Ready to Merge

#664 portoscarpart27 AND adds a modular file to include occulus areas, if needed!
  cev_eris.dme
  maps/CEVEris/Port_Oscar.dmm
  zzzz_modular_occulus/code/modules/game/areas/areablurb.dm
  zzzz_modular_occulus/maps/occulus_areas.dm
Labels: [REDACTED], Map Changes, Work in Progress

#667 Fixes Brigador Firemodes
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/plasma.dm
Labels: Balance/Rebalance, Ready to Merge

#668 Removing duplicate definition/override
  zzzz_modular_occulus/code/game/occulus-lore-fixes.dm
Labels: Quality of Life, Administrative, Ready to Merge

#671 Fixes some tool damage issues and other things
  code/datums/autolathe/biomatter.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/biomatter_manipulation/bioreactor/platform.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/hydroponics/trays/tray_reagents.dm
  icons/obj/storage/backpack.dmi
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/objects/items/tools/batons.dm
  zzzz_modular_occulus/code/modules/stashes/stashes.dm
Labels: Quality of Life, Bugfix, Ready to Merge

#672 Fixes a small error in bottle labeling
  code/modules/hydroponics/trays/tray_reagents.dm
Labels: [REDACTED], Quality of Life, Bugfix, Ready to Merge

#673 more bugfixes
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
Labels: Priority: High, Balance/Rebalance, Bugfix

#674 More support for toolmod bugfixes
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/knives.dm
  code/game/objects/items/weapons/tools/pickaxe.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/items/weapons/tools/weldingtools.dm
  zzzz_modular_occulus/code/game/objects/items/tools/batons.dm
Labels: Bugfix

#676 Upstream Cherrypicks: Updated Trade Stations, Scrap Magazines, Shotgun Shell Boxes, and Medscanner fixes
  cev_eris.dme
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/craft/recipes/guns.dm
  code/datums/loot_spawner.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/head/collectable.dm
  code/modules/economy/price_list.dm
  code/modules/materials/material_sheets.dm
  code/modules/mining/mine_items.dm
  code/modules/modular_computers/file_system/programs/generic/trade.dm
  code/modules/multiz/turf.dm
  code/modules/projectiles/ammunition/ammo_kits.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/energy/egun.dm
  code/modules/projectiles/guns/launcher/grenade_launcher.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/automatic/z8.dm
  code/modules/projectiles/guns/projectile/pistol/avasarala.dm
  code/modules/projectiles/guns/projectile/pistol/mandella.dm
  code/modules/projectiles/guns/projectile/revolver/deckard.dm
  code/modules/projectiles/guns/projectile/revolver/havelock.dm
  code/modules/projectiles/guns/projectile/revolver/mateba.dm
  code/modules/projectiles/guns/projectile/shotgun/bull.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/stashes/stash_types/weapons.dm
  code/modules/trade/datums/_trade_station.dm
  code/modules/trade/datums/trade_stations_presets/McRonalds.dm
  code/modules/trade/datums/trade_stations_presets/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/bluespace_tech.dm
  code/modules/trade/datums/trade_stations_presets/boozefood.dm
  code/modules/trade/datums/trade_stations_presets/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/fs_experimental_factory.dm
  code/modules/trade/datums/trade_stations_presets/fs_weapon_factory.dm
  code/modules/trade/datums/trade_stations_presets/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/illegalbeacon.dm
  code/modules/trade/datums/trade_stations_presets/material_refine.dm
  code/modules/trade/datums/trade_stations_presets/nt_cruisers.dm
  code/modules/trade/datums/trade_stations_presets/rigprovider.dm
  code/modules/trade/datums/trade_stations_presets/serbianship.dm
  code/modules/trade/datums/trade_stations_presets/suit_up.dm
  code/modules/trade/datums/trade_stations_presets/tb_cheapammofactorys.dm
  code/modules/trade/datums/trade_stations_presets/zarya.dm
  icons/obj/ammo.dmi
  icons/obj/ammo_mags.dmi
  icons/obj/ammo_speed.dmi
  zzzz_modular_occulus/code/modules/economy/vending.dm
  zzzz_modular_occulus/code/modules/projectiles/ammunition/magazines.dm
Labels: Feature, Ready for review, Bugfix

#677 Elevator 3.0
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/machinery/dorms_elevator.dm
Labels: Quality of Life, Ready for review, Bugfix

#684 Rebalance of SPUDs and Knockoff Roombas, and Engineering QOL
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/objects/items/devices/bosstown.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/roombattler.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/spud.dm
Labels: Quality of Life, Balance/Rebalance, Ready to Merge
