Repository Occulus-Server/Occulus-Eris, pull requests merged in 2022-01, with the labels that each got.

#799 Readjusts artwork oddity stats as they were still coming up jank
  code/game/machinery/autolathe/artist_bench.dm
  code/game/objects/items/devices/techno_tribalism.dm
Labels: Balance/Rebalance, Bugfix, Ready to Merge

#801 Removes comment, woohoo!
  code/game/world.dm
Labels: Ready to Merge

#802 Fixes the antag radio not having a sprite
  cev_eris.dme
  zzzz_modular_occulus/code/game/objects/items/devices/spy_bug.dm
Labels: Sprites, Bugfix, Ready to Merge

#806 Ship's nuke sets the alert to delta when armed
  code/game/machinery/nuclear_bomb.dm
Labels: Upstream Update, Feature, Ready for review

#804 fixes full auto firing when a gun should not be able to fire
  code/datums/datum_click_handlers.dm
Labels: Bugfix, Ready to Merge

#803 Litany tweaks
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  zzzz_modular_occulus/code/modules/core_implant/cruciform/rituals/base.dm
Labels: Quality of Life, Balance/Rebalance, Ready to Merge

#805 Fixes ghost/ClickOn()
  code/_onclick/ghost.dm
Labels: Bugfix, Ready to Merge

#807 Adds sink to chem, removes space chemmaster
  maps/CEVEris/_CEV_Eris.dmm
Labels: Balance/Rebalance, Map Changes, Ready to Merge

#809 Fixes assisted kidneys
  code/modules/organs/body_modifications.dm
Labels: Ready for review, Bugfix

#808 All belts can now hold bounce radios
  zzzz_modular_occulus/code/game/objects/items/weapons/storage/belt.dm
Labels: Ready for review, Balance/Rebalance

#810 Telesci Fixes
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/modules/telescience/telepad.dm
  zzzz_modular_occulus/code/modules/telescience/telepad_computer.dm
  zzzz_modular_occulus/code/modules/telescience/telepad_relay.dm
  zzzz_modular_occulus/code/modules/telescience/teleport_blocker.dm
  zzzz_modular_occulus/icons/obj/telescience.dmi
  zzzz_modular_occulus/sound/effects/telesci_inhibitor_alarm.ogg
  zzzz_modular_occulus/sound/effects/telesci_process.ogg
  zzzz_modular_occulus/sound/effects/telesci_sparkles.ogg
Labels: Sprites, Bugfix, Map Changes, Ready to Merge, Audio
