Repository Occulus-Server/Occulus-Eris, pull requests merged in 2022-08, with the labels that each got.

#892 Small integrated fixs
  code/__DEFINES/research.dm
  code/modules/integrated_electronics/core/debugger.dm
Labels: Balance/Rebalance, Bugfix

#893 Increased Laser Visibility
  icons/effects/projectiles.dmi
Labels: Sprites, Ready for review

#887 Adjusting Catalyst Core recipe
  zzzz_modular_occulus/code/datums/craft/recipes/guns.dm
Labels: Ready for review, Balance/Rebalance

#895 Removes mapstart muzzle and straightjacket
  maps/CEVEris/_CEV_Eris.dmm
Labels: Quality of Life, Ready for review, Balance/Rebalance

#896 Adds several new emote sounds
  code/modules/mob/living/carbon/human/emote.dm
  zzzz_modular_occulus/sound/voice/YeenCackle.ogg
  zzzz_modular_occulus/sound/voice/cat_purr.ogg
  zzzz_modular_occulus/sound/voice/cat_purr_long.ogg
  zzzz_modular_occulus/sound/voice/coyoteawoo.ogg
  zzzz_modular_occulus/sound/voice/coyoteawoo2.ogg
  zzzz_modular_occulus/sound/voice/coyoteawoo3.ogg
  zzzz_modular_occulus/sound/voice/coyoteawoo4.ogg
  zzzz_modular_occulus/sound/voice/coyoteawoo5.ogg
  zzzz_modular_occulus/sound/voice/foxbark.ogg
  zzzz_modular_occulus/sound/voice/geck.ogg
  zzzz_modular_occulus/sound/voice/growl.ogg
  zzzz_modular_occulus/sound/voice/lynx.ogg
  zzzz_modular_occulus/sound/voice/manlaugh1.ogg
  zzzz_modular_occulus/sound/voice/manlaugh2.ogg
  zzzz_modular_occulus/sound/voice/merp.ogg
  zzzz_modular_occulus/sound/voice/weh_1.ogg
  zzzz_modular_occulus/sound/voice/wolfhowl.ogg
  zzzz_modular_occulus/sound/voice/womanlaugh.ogg
  zzzz_modular_occulus/sound/voice/yap.ogg
Labels: Ready for review, Audio

#898 Skremfix, Barricade fix
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/composer.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/conservator.dm
Labels: 👥 Impact: I-3 Some, Bugfix

#907 Bugfixes
  code/modules/mob/living/simple_animal/hostile/stranger.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/storage/pouches.dm
Labels: Ready for review, Bugfix

#908 [REDACTED] the [REDACTED] and [DATA EXPUNGED]
  zzzz_modular_occulus/code/game/machinery/bsd.dm
Labels: [REDACTED], Feature, Ready for review

#900 Fixes synthetics sending soulcrypts to the shadow realm
  code/modules/core_implant/cruciform/machinery/cloning.dm
Labels: Bugfix
