Repository Occulus-Server/Occulus-Eris, pull requests merged in 2022-03, with the labels that each got.

#842 Quick and dirty fix
  code/game/objects/random/traps/traps.dm
Labels: Bugfix

#849 'bugfixes'
  cev_eris.dme
  code/game/gamemodes/events/hidden_events/kaiser.dm
  icons/mob/mob.dmi
  zzzz_modular_occulus/code/modules/mob/living/carbon/superior_animal/roach/kaiserin.dm
  zzzz_modular_occulus/icons/mob/kaiserin.dmi
  zzzz_modular_occulus/sound/weapons/guns/fire/minigun_fire.ogg
Labels: Ready for review, Code Feature

#848 Siren event fixes+conservator update
  zzzz_modular_occulus/code/game/gamemodes/events/siren_scan.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/augmentor.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/conservator.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/replicant.dm
  zzzz_modular_occulus/code/modules/projectiles/projectile/projectile.dm
  zzzz_modular_occulus/icons/mob/siren/general.dmi
  zzzz_modular_occulus/icons/obj/traps.dmi
Labels: Ready for review, Bugfix, Code Feature

#850 Removal of blatant debug to_worlds
  zzzz_modular_occulus/code/game/gamemodes/events/siren_scan.dm
Labels: Priority: High, 👥 Impact: I-3 Some, Ready for review

#851 ensign tweaks
  zzzz_modular_occulus/code/game/jobs/job/captain.dm
Labels: Balance/Rebalance

#857 Hotfix for allowing humans to spawn
  code/modules/mob/living/carbon/human/species/station/station_vr.dm
Labels: Bugfix

#829 Katana changes
  code/game/objects/items/weapons/tools/simple_weapons.dm
  icons/inventory/belt/mob.dmi
  icons/inventory/on_suit/mob.dmi
  zzzz_modular_occulus/code/game/objects/items/weapons/storage/pouches.dm
Labels: Balance/Rebalance

#852 Update science.dm
  zzzz_modular_occulus/code/game/jobs/job/science.dm
Labels: Lore Compliance, Balance/Rebalance, Ready to Merge

#854 Fixes a bug that corrupts a crafting step
  code/datums/craft/step.dm
Labels: Bugfix, Ready to Merge
