Repository Occulus-Server/Occulus-Eris, pull requests merged in 2022-12, with the labels that each got.

#899 Tools and RPEDs no longer can be blended by grinders.
  code/modules/reagents/machinery/grinder.dm
Labels: Bugfix

#923 Clumsily Adds A Rudementary Implant
  zzzz_modular_occulus/code/modules/loadout/lists/misc.dm
Labels: Feature, Modular

#926 Notrip!
  zzzz_modular_occulus/code/game/turfs/flooring/flooring.dm
Labels: Feature, Modular

#921 Railguns v2
  cev_eris.dme
  code/__DEFINES/components.dm
  code/__DEFINES/materials.dm
  code/_onclick/click.dm
  code/modules/materials/materials.dm
  code/modules/projectiles/gun.dm
  code/modules/scrap/scrap_burner.dm
  code/modules/scrap/scrap_refine.dm
  code/modules/scrap/scrap_refinery.dm
  code/modules/scrap/scrap_stacker.dm
  zzzz_modular_occulus/code/datums/components/heat.dm
  zzzz_modular_occulus/code/datums/craft/recipes/misc.dm
  zzzz_modular_occulus/code/modules/projectiles/guns/energy/railgun.dm
  zzzz_modular_occulus/code/modules/projectiles/projectile/bullettypes.dm
  zzzz_modular_occulus/code/modules/research/designs.dm
  zzzz_modular_occulus/code/modules/research/nodes/combat.dm
  zzzz_modular_occulus/icons/obj/guns/energy/gauss.dmi
  zzzz_modular_occulus/icons/obj/guns/energy/railgun.dmi
  zzzz_modular_occulus/sound/weapons/guns/fire/gaussrifle.ogg
  zzzz_modular_occulus/sound/weapons/guns/interact/gauss_vent.ogg
  zzzz_modular_occulus/sound/weapons/rail.ogg
Labels: Feature, Sprites, Ready for review

#928 Ticks railgun file
  cev_eris.dme
Labels: Ready for review, Bugfix

#932 Adds in a new type of candle
  cev_eris.dme
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
  zzzz_modular_occulus/code/game/machinery/vending.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/mekcandle.dm
  zzzz_modular_occulus/icons/obj/mekcandle.dmi
Labels: Lore, Modular, Ready for review

#933 Oops all Theomat
  zzzz_modular_occulus/code/game/machinery/vending.dm
Labels: Bugfix
