Repository Occulus-Server/Occulus-Eris, pull requests merged in 2022-02, with the labels that each got.

#816 Unfuckers the deepmaint nuke
  maps/submaps/deepmaint_rooms/core/vault.dmm
Labels: Priority: High, ⚠️ Severity: S-1 Severe, 👥 Impact: I-1 All, Bugfix, Map Changes, Ready to Merge

#815 Ports the second overmap update from Eris, and tacks on some extra sciencey stuff on top
  cev_eris.dme
  code/__HELPERS/global_lists.dm
  code/controllers/subsystems/trade.dm
  code/game/area/asteroid_areas.dm
  code/game/gamemodes/events/weather/rad_storm.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/unsimulated/floor.dm
  code/global.dm
  code/modules/dungeons/junk_tractor_beam.dm
  code/modules/long_range_scanner/long_range_scanner.dm
  code/modules/mob/mob.dm
  code/modules/overmap/_defines.dm
  code/modules/overmap/events/event.dm
  code/modules/overmap/events/movable.dm
  code/modules/overmap/exoplanets/exoplanet.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/overmap/ships/ship.dm
  code/modules/shield_generators/shield_generator.dm
  code/modules/shuttles/landmarks.dm
  code/modules/shuttles/shuttle.dm
  code/modules/trade/datums/_trade_station.dm
  icons/obj/overmap.dmi
  maps/CEVEris/overmap-eris.dm
  maps/encounters/blacksite/blacksite.dm
  maps/encounters/blacksite/blacksite_large.dmm
  maps/encounters/blacksite/blacksite_large_chunk.dmm
  maps/encounters/blacksite/blacksite_medium.dmm
  maps/encounters/blacksite/blacksite_medium_chunk.dmm
  maps/encounters/blacksite/blacksite_small.dmm
  maps/encounters/blacksite/blacksite_small_chunk.dmm
  maps/submaps/junk_field/j25_25/ironhammer/ironhammer1.dmm
  maps/submaps/junk_field/j25_25/ironhammer/ironhammer2.dmm
  maps/submaps/junk_field/j25_25/ironhammer/ironhammer3.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral1.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral2.dmm
  maps/submaps/junk_field/j25_25/neutral/neutral3.dmm
  maps/submaps/junk_field/j25_25/onestar/onestar1.dmm
  maps/submaps/junk_field/j25_25/onestar/onestar2.dmm
  maps/submaps/junk_field/j25_25/onestar/onestar3.dmm
  maps/submaps/junk_field/j25_25/onestar/onestar4.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian1.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian2.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian3.dmm
  maps/submaps/junk_field/j25_25/spacewrecks/spacewrecks.dm
  maps/submaps/junk_field/j25_25/spacewrecks/spacewrecks1.dmm
  maps/submaps/junk_field/j25_25/spacewrecks/spacewrecks2.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral1.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral10.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral11.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral2.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral3.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral4.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral5.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral6.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral7.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral8.dmm
  maps/submaps/junk_field/j5_5/neutral/neutral9.dmm
  nano/templates/helm.tmpl
Labels: Upstream Update, Feature, Ready for review

#819 Fixed a merge conflict
  maps/submaps/junk_field/j25_25/ironhammer/ironhammer3.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian3.dmm
Labels: Administrative, Bugfix

#825 Correct .20 rubber ammobox name
  code/modules/projectiles/ammunition/boxes.dm
Labels: Quality of Life, Ready for review

#818 New sprites from upstream (and minor changes)
  code/game/machinery/vending.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/implant/implant.dm
  code/game/objects/items/weapons/implant/implantcase.dm
  code/game/objects/items/weapons/implant/implanter.dm
  code/game/objects/items/weapons/implant/implantpad.dm
  code/game/objects/items/weapons/implant/implants/chemical.dm
  code/game/objects/items/weapons/implant/implants/compressed.dm
  code/game/objects/items/weapons/implant/implants/death_alarm.dm
  code/game/objects/items/weapons/implant/implants/excelsior.dm
  code/game/objects/items/weapons/implant/implants/explosive.dm
  code/game/objects/items/weapons/implant/implants/freedom.dm
  code/game/objects/items/weapons/implant/implants/spying.dm
  code/game/objects/items/weapons/implant/implants/tracking.dm
  code/game/objects/items/weapons/implant/implants/uplink.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/turfs/initialization/maintenance.dm
  code/modules/economy/cash.dm
  code/modules/economy/price_list.dm
  code/modules/materials/material_sheets.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/food-Drinks.dm
  icons/effects/projectiles.dmi
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/back/mob.dmi
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/atmos.dmi
  icons/obj/autopsy_scanner.dmi
  icons/obj/candle.dmi
  icons/obj/cigarettes.dmi
  icons/obj/device.dmi
  icons/obj/drinks.dmi
  icons/obj/flamethrower.dmi
  icons/obj/food.dmi
  icons/obj/items.dmi
  icons/obj/large_syringe.dmi
  icons/obj/lighting.dmi
  icons/obj/objects.dmi
  icons/obj/reagentfillings.dmi
  icons/obj/singularity.dmi
  icons/obj/stack/items.dmi
  icons/obj/stack/material.dmi
  icons/obj/syringe.dmi
  icons/obj/trash.dmi
  icons/obj/weapons.dmi
  zzzz_modular_occulus/code/game/machinery/vending.dm
Labels: Upstream Update, Sprites, Ready to Merge

#812 Xenoarchaeology fixes and Remap
  cev_eris.dme
  code/controllers/subsystems/xenoarch.dm
  code/modules/research/xenoarchaeology/anomaly_container.dm
  code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
  code/modules/research/xenoarchaeology/machinery/artifact_harvester.dm
  code/modules/research/xenoarchaeology/tools/ano_device_battery.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/game/machinery/atmoalter/area_atmos_computer.dm
  zzzz_modular_occulus/icons/obj/xenoarchaeology.dmi
Labels: Feature, Balance/Rebalance, Bugfix, Map Changes, Ready to Merge

#824 NVG Battery
  code/modules/clothing/glasses/night.dm
  code/modules/clothing/head/armor.dm
Labels: Ready for review, Balance/Rebalance

#821 Expanded markings V3 or so
  zzzz_modular_occulus/code/modules/sprite_accessories/_accessories_sprite.dm
  zzzz_modular_occulus/code/modules/sprite_accessories/_accessory_hair.dm
  zzzz_modular_occulus/icons/mob/jamini-markings.dmi
Labels: Feature, Quality of Life, Sprites, Bugfix, Ready to Merge

#827 Attempt to fix reader.dm runtimes
  code/modules/maps/tg/reader.dm
Labels: Bugfix

#828 Fixes "Get-Server-Log" not working if server hits midnight during a round
  code/modules/admin/verbs/getlogs.dm
Labels: Ready for review, Administrative, Bugfix

#831 fixed/second attempt at empty meadow deepmaint
  zzzz_modular_occulus/maps/submaps/deepmaint_rooms/core/core_rooms.dm
  zzzz_modular_occulus/maps/submaps/deepmaint_rooms/core/empty_meadow.dmm
Labels: Map Changes

#839 Fixes dmdocs
  .github/workflows/generate_documentation.yml
Labels: Ready for review, Github/Discord

#838 Snacc Time: The Triumphant Return of Syndi-Cakes
  cev_eris.dme
  code/modules/reagents/reagent_containers/food/snacks.dm
  zzzz_modular_occulus/code/game/machinery/vending.dm
  zzzz_modular_occulus/code/game/objects/items/trash.dm
  zzzz_modular_occulus/code/modules/reagents/reagent_containers/food/snacks.dm
  zzzz_modular_occulus/icons/obj/food.dmi
  zzzz_modular_occulus/icons/obj/trash.dmi
Labels: Feature, Quality of Life, Sprites, Modular, Balance/Rebalance, Ready to Merge

#837 The Big Shemaugh and Beret Update
  zzzz_modular_occulus/code/modules/client/preference_setup/loadout/lists/headwear.dm
  zzzz_modular_occulus/code/modules/clothing/head/head.dm
  zzzz_modular_occulus/code/modules/clothing/masks/masks.dm
  zzzz_modular_occulus/icons/inventory/head/icon.dmi
  zzzz_modular_occulus/icons/inventory/head/mob.dmi
  zzzz_modular_occulus/icons/inventory/mask/icon.dmi
  zzzz_modular_occulus/icons/inventory/mask/mob.dmi
Labels: Quality of Life, Sprites, Modular, Ready for review

#833 2022 Febuary Ports - Part 1
  cev_eris.dme
  code/datums/autolathe/ammo.dm
  code/datums/autolathe/circuits.dm
  code/datums/autolathe/clothing.dm
  code/datums/autolathe/guns.dm
  code/datums/craft/recipes/tools.dm
  code/game/machinery/excelsior/ex_teleporter.dm
  code/game/machinery/excelsior/ex_turret.dm
  code/game/machinery/vending.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/organ_module/active/multitool/improvised.dm
  code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm
  code/game/objects/items/weapons/design_disks/asters.dm
  code/game/objects/items/weapons/design_disks/excelsior.dm
  code/modules/clothing/head/armor.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/mob_grab.dm
  code/modules/mob/mob_grab_specials.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/reagents/recipes.dm
  icons/inventory/uniform/mob.dmi
  icons/obj/guns/projectile/maxim.dmi
  icons/obj/surgery.dmi
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/generic.dm
Labels: Upstream Update, Ready to Merge

#834 2022 Febuary Ports - Part 2
  code/game/area/asteroid_areas.dm
  code/game/objects/effects/spawners/ghostroles.dm
  code/game/objects/effects/spawners/ghostspawner.dm
  maps/encounters/prisonhulk/prisonhulk.dm
  maps/encounters/prisonhulk/prisonhulk.dmm
Labels: Upstream Update, Ready to Merge

#830 Traitor Gear Additions, Part 1
  cev_eris.dme
  code/datums/repositories/crew/crew.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/carbon/human/stripping.dm
  zzzz_modular_occulus/code/datums/craft/recipes/furniture.dm
  zzzz_modular_occulus/code/datums/craft/recipes/guns.dm
  zzzz_modular_occulus/code/datums/craft/recipes/tools.dm
  zzzz_modular_occulus/code/datums/craft/recipes/weapon.dm
  zzzz_modular_occulus/code/datums/language/merc.dm
  zzzz_modular_occulus/code/datums/uplink/devices and tools.dm
  zzzz_modular_occulus/code/datums/uplink/highly visible and dangerous weapons.dm
  zzzz_modular_occulus/code/datums/uplink/stealthy and inconspicuous weapons.dm
  zzzz_modular_occulus/code/datums/wires/bomb.dm
  zzzz_modular_occulus/code/game/machinery/bomb.dm
  zzzz_modular_occulus/code/game/objects/effects/temporary_visual.dm
  zzzz_modular_occulus/code/game/objects/items/devices/cloakingfield.dm
  zzzz_modular_occulus/code/game/objects/items/devices/traitor_devices.dm
  zzzz_modular_occulus/code/game/objects/items/pizzabomb.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/syndie.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/traitor_weapons.dm
  zzzz_modular_occulus/code/modules/clothing/gloves/sneak.dm
  zzzz_modular_occulus/code/modules/soulcrypt/modules/squawk.dm
  zzzz_modular_occulus/icons/obj/bomb.dmi
  zzzz_modular_occulus/icons/obj/device.dmi
  zzzz_modular_occulus/icons/obj/food.dmi
  zzzz_modular_occulus/icons/obj/guns/projectile.dmi
  zzzz_modular_occulus/icons/obj/weapons.dmi
  zzzz_modular_occulus/sound/items/timer.ogg
  zzzz_modular_occulus/sound/weapons/resonator_blast.ogg
Labels: Feature, Sprites, Ready for review

#835 2022 Febuary Ports Part 3
  code/__DEFINES/items.dm
  code/datums/perks/oddity.dm
  code/datums/uplink/highly visible and dangerous weapons.dm
  code/game/objects/items/devices/von-krabin.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/launcher/projectile_grenade_launcher.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
  code/modules/projectiles/guns/projectile/shotgun/regulator.dm
  code/modules/projectiles/guns/projectile/shotgun/sawnoff.dm
  code/modules/reagents/enricher.dm
  icons/obj/guns/energy/obrez_retro.dmi
  icons/obj/guns/mods.dmi
  icons/obj/guns/projectile/obrez_bolt.dmi
  icons/obj/guns/projectile/obrez_sg.dmi
Labels: Upstream Update, Ready to Merge
