Repository Occulus-Server/Occulus-Eris, pull requests merged in 2022-04, with the labels that each got.

#862 More hoodie colours
  cev_eris.dme
  zzzz_modular_occulus/code/modules/clothing/suit/miscellaneous.dm
  zzzz_modular_occulus/icons/inventory/suit/icon.dmi
  zzzz_modular_occulus/icons/inventory/suit/mob.dmi
  zzzz_modular_occulus/icons/inventory/suit/mob_fem.dmi
Labels: Quality of Life, Sprites, Ready to Merge

#863 IC printer R&D Fix
  code/modules/research/designs/custom_circuits.dm
Labels: Bugfix, Ready to Merge

#865 Fragmentation can now hit roaches
  cev_eris.dme
  zzzz_modular_occulus/code/game/objects/items/weapons/grenades/stinger.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/superior_animal/defense.dm
  zzzz_modular_occulus/code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance/Rebalance, Bugfix, Ready to Merge

#869 Bugfixes - Water, Slimes, and Defibs
  code/modules/mob/living/carbon/slime/powers.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/living.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/reagents/random.dm
  zzzz_modular_occulus/code/modules/defib.dm
Labels: Quality of Life, Balance/Rebalance, Bugfix, Ready to Merge

#866 Makes Frioline useful
  zzzz_modular_occulus/code/modules/reagents/reagents/other.dm
Labels: Balance/Rebalance, Ready to Merge

#860 Sig cooking update
  cev_eris.dme
  zzzz_modular_occulus/code/game/machinery/vending.dm
  zzzz_modular_occulus/code/modules/cooking/meal.dm
  zzzz_modular_occulus/icons/obj/food.dmi
Labels: Feature, Modular, Ready to Merge

#867 Fixes Trays
  code/game/objects/items/weapons/trays.dm
Labels: Quality of Life, Bugfix, Ready to Merge

#871 Fixes some missing sprites
  code/game/objects/items/devices/uplink.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/virus2/items_devices.dm
  icons/obj/drinks.dmi
Labels: Sprites, Bugfix, Ready to Merge
