Repository Occulus-Server/Occulus-Eris, pull requests merged in 2022-09, with the labels that each got.

#916 Fixing runtimes
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  code/modules/reagents/reagents.dm
Labels: Bugfix

#914 The Paco Fun Switch
  code/__DEFINES/items.dm
  code/modules/projectiles/guns/projectile/pistol/paco.dm
  icons/obj/guns/mods.dmi
  zzzz_modular_occulus/code/modules/projectiles/guns/mods/mods.dm
Labels: Feature

#917 Custom blood colors
  code/game/atoms.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/structures/medical_stand.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/blood.dm
  code/modules/organs/external/dismemberment.dm
  code/modules/projectiles/projectile.dm
  zzzz_modular_occulus/code/game/gamemodes/occultist/occultist_powers.dm
  zzzz_modular_occulus/code/modules/client/preference_setup/loadout/01_basic.dm
  zzzz_modular_occulus/code/modules/client/preference_setup/loadout/02_body.dm
  zzzz_modular_occulus/code/modules/client/preferences.dm
Labels: Feature, Bugfix
