Repository Occulus-Server/Occulus-Eris, pull requests merged in 2022-05, with the labels that each got.

#872 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Ready to Merge, Github/Discord

#874 Fixes slimepeople missing stomachs
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/species/station.dm
Labels: Modular, Balance/Rebalance, Bugfix, Ready to Merge

#876 Glass stack
  code/modules/materials/material_sheets.dm
  icons/obj/stack/material.dmi
Labels: Upstream Update, Sprites, Ready for review, Bugfix

#877 Makes stingers require chems
  zzzz_modular_occulus/code/game/objects/items/weapons/grenades/stinger.dm
  zzzz_modular_occulus/code/modules/reagents/reagents/other.dm
  zzzz_modular_occulus/code/modules/reagents/recipes.dm
Labels: Balance/Rebalance, Ready to Merge

#870 Adds fishing hats
  cev_eris.dme
  zzzz_modular_occulus/code/modules/client/preference_setup/loadout/lists/headwear.dm
  zzzz_modular_occulus/code/modules/clothing/head/fishing.dm
  zzzz_modular_occulus/icons/inventory/head/item_fishing.dmi
  zzzz_modular_occulus/icons/inventory/head/mob_fishing.dmi
Labels: Feature, Sprites, Ready for review

#875 Flashbang Fix
  cev_eris.dme
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/sword_of_truth.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  zzzz_modular_occulus/code/modules/clothing/clothing.dm
  zzzz_modular_occulus/code/modules/clothing/head/armor.dm
  zzzz_modular_occulus/code/modules/clothing/head/head.dm
  zzzz_modular_occulus/code/modules/clothing/mekhanearmor.dm
  zzzz_modular_occulus/code/modules/clothing/occarmor.dm
  zzzz_modular_occulus/code/modules/clothing/spacesuits/bomb.dm
  zzzz_modular_occulus/code/modules/clothing/spacesuits/captain.dm
  zzzz_modular_occulus/code/modules/clothing/spacesuits/rig/rig_pieces.dm
  zzzz_modular_occulus/code/modules/clothing/spacesuits/syndi.dm
  zzzz_modular_occulus/code/modules/clothing/spacesuits/void/excelsior.dm
  zzzz_modular_occulus/code/modules/clothing/spacesuits/void/merc.dm
  zzzz_modular_occulus/code/modules/clothing/spacesuits/void/station.dm
  zzzz_modular_occulus/code/modules/clothing/spacesuits/void/wizard.dm
  zzzz_modular_occulus/code/modules/core_implant/cruciform/rituals/base.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/carbon.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/human.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/human_defines.dm
Labels: Modular, Balance/Rebalance, Bugfix, Ready to Merge, Code Feature

#878 Medical Tweaks
  code/modules/organs/internal/internal_organ_processes.dm
  code/modules/reagents/reagents/nanites.dm
  zzzz_modular_occulus/code/datums/autolathe/biomatter.dm
  zzzz_modular_occulus/code/game/objects/items/stacks/medical.dm
Labels: Balance/Rebalance, Bugfix, Ready to Merge

#873 Allows players to holster hammers onto their suits.
  zzzz_modular_occulus/code/game/objects/items/weapons/storage/pouches.dm
Labels: Bugfix, Ready to Merge
