Repository Occulus-Server/Occulus-Eris, pull requests merged in 2023-07, with the labels that each got.

#1039 Jukebox Additions
  cev_eris.dme
  code/_global_vars/lists/flavor.dm
  code/datums/music_tracks/engage.dm
  code/datums/music_tracks/toys4bob.dm
  sound/music/YearsLate.ogg
  sound/music/Yehat_theme_music.ogg
  sound/music/transit.ogg
Labels: Ready for review, Code Feature, Audio

#1040 Revert "Jukebox Additions"
  cev_eris.dme
  code/_global_vars/lists/flavor.dm
  code/datums/music_tracks/engage.dm
  code/datums/music_tracks/toys4bob.dm
  sound/music/YearsLate.ogg
  sound/music/Yehat_theme_music.ogg
  sound/music/transit.ogg
Labels: Ready to Merge

#1038 removes the turret from chromelab.dmm
  zzzz_modular_occulus/maps/submaps/deepmaint_rooms/core/chromelab.dmm
Labels: Ready for review, Map Changes

#1037 Fix spacespice batter and beerbatter path
  zzzz_modular_occulus/code/modules/reagents/food-Drinks.dm
Labels: Bugfix

#1051 Xenobio adjustments
  code/modules/mob/living/carbon/slime/subtypes.dm
  code/modules/reagents/recipes.dm
  code/modules/research/experiment.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Balance/Rebalance, Bugfix

#1053 Tweaks/fixes some issues in the club maints
  maps/CEVEris/_CEV_Eris.dmm
Labels: Bugfix
