Repository Occulus-Server/Occulus-Eris, pull requests merged in 2023-05, with the labels that each got.

#990 Fix: Autodocs can remove shrapnel now.
  code/modules/surgery/autodoc.dm
Labels: Ready for review, Bugfix

#989 Add stomach pump to sleeper
  code/game/machinery/Sleeper.dm
  nano/templates/sleeper.tmpl
Labels: Feature, Ready for review

#998 subtle emote!
  cev_eris.dme
  zzzz_modular_occulus/code/modules/mob/emote.dm
Labels: Feature, Ready for review

#996 Port Kitsune Tails
  code/modules/sprite_accessories/sprite_accessories_vr.dm
  icons/mob/vore/tails_vr.dmi
Labels: Feature

#997 Upstream Grenades: HESH Rocket, Buffed Fragmentation, Pipebomb, WP & Fix
  cev_eris.dme
  code/datums/craft/recipes/weapon.dm
  code/datums/uplink/grenades.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/explosion.dm
  code/game/objects/items/weapons/grenades/frag.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/turfs/simulated/walls.dm
  code/modules/mob/living/living_defense.dm
  code/modules/multiz/turf.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/fragment.dm
  code/modules/projectiles/projectile/projectilegrenades.dm
  code/modules/projectiles/projectile/special.dm
  icons/obj/ammo.dmi
  icons/obj/grenade.dmi
  icons/obj/projectiles_64x64.dmi
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/datums/uplink/grenades.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/grenades/stinger.dm
  zzzz_modular_occulus/code/modules/projectiles/ammunition/bullets.dm
  zzzz_modular_occulus/code/modules/projectiles/projectile/bullettypes.dm
  zzzz_modular_occulus/code/modules/research/nodes/combat.dm
  zzzz_modular_occulus/icons/obj/stinger.dmi
Labels: Feature, Bugfix

#1003 BLUESPACE IS BLU
  code/controllers/evacuation/evacuation.dm
  icons/parallax.dmi
Labels: Sprites, Ready for review
