Repository Occulus-Server/Occulus-Eris, pull requests merged in 2023-06, with the labels that each got.

#1009 Update effects.dm
  code/modules/projectiles/effects.dm
Labels: Bugfix

#1010 Breakdown Rework Part 1: Simple Progressive Breakdown
  cev_eris.dme
  code/modules/sanity/breakdown.dm
  code/modules/sanity/sanity_mob.dm
  zzzz_modular_occulus/code/modules/sanity/breakdowns.dm
  zzzz_modular_occulus/code/modules/sanity/sanity_mob.dm
Labels: Feature, Balance/Rebalance

#1012 Fix alcohol price fix
  zzzz_modular_occulus/code/modules/economy/price_list_fixed.dm
Labels: Bugfix

#1015 Small rebalances and fixes
  cev_eris.dme
  code/__DEFINES/perks.dm
  code/datums/perks/job.dm
  code/datums/setup_option/backgrounds/fate.dm
  zzzz_modular_occulus/code/datums/setup_option/backgrounds/fate.dm
  zzzz_modular_occulus/code/game/objects/items/devices/bosstown.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/nanotrasen.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/roombattler.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/spud.dm
Labels: Balance/Rebalance, Bugfix

#1016 Traitor item: Portable Autodoc
  zzzz_modular_occulus/code/datums/uplink/medical.dm
  zzzz_modular_occulus/code/game/machinery/autodoc.dm
  zzzz_modular_occulus/icons/obj/portadoc.dmi
Labels: Feature, Code Feature

#1017 Fixes Pump-action runtimes from Shotslot's existance
  zzzz_modular_occulus/code/modules/projectiles/guns/projectile/shotgun/pump.dm
Labels: Bugfix

#1008 The BIG KITCHEN UPDATE: Part One, the machines and food
  cev_eris.dme
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  sound/effects/meatsizzle.ogg
  sound/machines/hatch_open.ogg
  zzzz_modular_occulus/code/_DEFINES/cooking.dm
  zzzz_modular_occulus/code/__HELPERS/kitchen.dm
  zzzz_modular_occulus/code/game/machinery/appliance.dm
  zzzz_modular_occulus/code/game/machinery/kitchen/containers.dm
  zzzz_modular_occulus/code/game/machinery/kitchen/cooker.dm
  zzzz_modular_occulus/code/game/machinery/kitchen/cooker_output.dm
  zzzz_modular_occulus/code/game/machinery/kitchen/fryer.dm
  zzzz_modular_occulus/code/game/machinery/kitchen/grill.dm
  zzzz_modular_occulus/code/game/machinery/kitchen/mixer.dm
  zzzz_modular_occulus/code/game/machinery/kitchen/oven.dm
  zzzz_modular_occulus/code/game/machinery/kitchen/stove.dm
  zzzz_modular_occulus/code/game/machinery/kitchen_new.dm
  zzzz_modular_occulus/code/game/machinery/kitchen_old.dm
  zzzz_modular_occulus/code/modules/cooking/recipes/recipe.dm
  zzzz_modular_occulus/code/modules/cooking/recipes/recipes_mix.dm
  zzzz_modular_occulus/code/modules/cooking/recipes/recipes_sol.dm
  zzzz_modular_occulus/code/modules/cooking/recipes/recipies_baked.dm
  zzzz_modular_occulus/code/modules/cooking/recipes/recipies_breads.dm
  zzzz_modular_occulus/code/modules/cooking/recipes/recipies_breakfast.dm
  zzzz_modular_occulus/code/modules/cooking/recipes/recipies_fryer.dm
  zzzz_modular_occulus/code/modules/cooking/recipes/recipies_grill.dm
  zzzz_modular_occulus/code/modules/cooking/recipes/recipies_meat.dm
  zzzz_modular_occulus/code/modules/cooking/recipes/recipies_mix.dm
  zzzz_modular_occulus/code/modules/cooking/recipes/recipies_pan.dm
  zzzz_modular_occulus/code/modules/cooking/recipes/recipies_pastries.dm
  zzzz_modular_occulus/code/modules/cooking/recipes/recipies_soup.dm
  zzzz_modular_occulus/code/modules/cooking/snacks.dm
  zzzz_modular_occulus/code/modules/food/kitchen/bakedfood.dm
  zzzz_modular_occulus/code/modules/food/kitchen/breadsfood.dm
  zzzz_modular_occulus/code/modules/food/kitchen/breakfastfood.dm
  zzzz_modular_occulus/code/modules/food/kitchen/fryerfood.dm
  zzzz_modular_occulus/code/modules/food/kitchen/grillfood.dm
  zzzz_modular_occulus/code/modules/food/kitchen/meatfood.dm
  zzzz_modular_occulus/code/modules/food/kitchen/mixfood.dm
  zzzz_modular_occulus/code/modules/food/kitchen/panfood.dm
  zzzz_modular_occulus/code/modules/food/kitchen/pastriesfood.dm
  zzzz_modular_occulus/code/modules/food/kitchen/solfood.dm
  zzzz_modular_occulus/code/modules/food/kitchen/soupfood.dm
  zzzz_modular_occulus/code/modules/hydroponics/grown.dm
  zzzz_modular_occulus/code/modules/reagents/food-Drinks.dm
  zzzz_modular_occulus/code/modules/reagents/reagent_containers/food/snacks.dm
  zzzz_modular_occulus/code/modules/reagents/reagent_containers/kitchen.dm
  zzzz_modular_occulus/icons/obj/kitchen_update/baked.dmi
  zzzz_modular_occulus/icons/obj/kitchen_update/food.dmi
  zzzz_modular_occulus/icons/obj/kitchen_update/food_custom.dmi
  zzzz_modular_occulus/icons/obj/kitchen_update/food_ingredients.dmi
  zzzz_modular_occulus/icons/obj/machines/kitchen.dmi
Labels: Feature, Sprites, Ready for review, Framework Ground Zero

#1020 babe, wake up- new airlock just dropped
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/shuttles-eris.dm
Labels: Ready for review, Map Changes

#1021 Cyto-Revitalization Basin and Resuscitator now revive simple animals.…
  code/modules/core_implant/cruciform/machinery/vat.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/replicant.dm
  zzzz_modular_occulus/code/modules/reagents/reagents/other.dm
Labels: Feature

#1026 fixes that one fucking spoit near cargogogog
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes

#1025 Give Engineering Equipment (Reactor) access to ensign
  zzzz_modular_occulus/code/game/jobs/job/captain.dm
Labels: Bugfix

#1024 Remove respawn timers
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/observer/ghost/ghost.dm
Labels: Feature

#1023 Readd wounds disappearing after 10 minutes
  code/modules/organs/external/_external.dm
Labels: Feature

#1018 Siren Event Overhaul
  cev_eris.dme
  code/modules/reagents/reagents/core.dm
  zzzz_modular_occulus/code/game/gamemodes/events/siren_scan.dm
  zzzz_modular_occulus/code/game/objects/explosion.dm
  zzzz_modular_occulus/code/game/objects/items/weapons/secrets.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/human.dm
  zzzz_modular_occulus/code/modules/mob/living/carbon/human/human_defense.dm
  zzzz_modular_occulus/code/modules/mob/living/living_defense.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/amalgamate.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/augmentor.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/composer.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/conservator.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/intruder.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/nemesis.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/replicant.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/siren.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/turret.dm
  zzzz_modular_occulus/code/modules/projectiles/projectile/projectile.dm
  zzzz_modular_occulus/code/modules/reagents/reagents/other.dm
  zzzz_modular_occulus/icons/effects/beam.dmi
  zzzz_modular_occulus/icons/mob/siren/conservator.dmi
  zzzz_modular_occulus/icons/mob/siren/general.dmi
  zzzz_modular_occulus/icons/mob/siren/nemesis.dmi
  zzzz_modular_occulus/sound/effects/IT_arrives.wav
  zzzz_modular_occulus/sound/effects/beamcharge.ogg
  zzzz_modular_occulus/sound/effects/beamfire.ogg
  zzzz_modular_occulus/sound/effects/dronehover.ogg
  zzzz_modular_occulus/sound/effects/lightningbolt.ogg
  zzzz_modular_occulus/sound/effects/nanitechittering.ogg
  zzzz_modular_occulus/sound/effects/oraclespeak.ogg
  zzzz_modular_occulus/sound/effects/oraclespeak2.ogg
  zzzz_modular_occulus/sound/effects/oraclespeak3.ogg
  zzzz_modular_occulus/sound/effects/ship-grade beam weapon.ogg
  zzzz_modular_occulus/sound/effects/stridergrowl.ogg
  zzzz_modular_occulus/sound/effects/striderwalk.wav
Labels: Documentation, Feature, Bugfix, Code Cleanup, Code Feature, Audio

#1027 Add embedded claws to research
  cev_eris.dme
  zzzz_modular_occulus/code/modules/research/designs/prosthesis_implants.dm
  zzzz_modular_occulus/prosthesis/implementation.dm
Labels: Feature

#1028 Extra clarification
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/amalgamate.dm
Labels: Quality of Life, ⚠️ Severity: S-5 Trivial

#1031 Sirenmob HotFix
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/nemesis.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/siren.dm
  zzzz_modular_occulus/code/modules/projectiles/projectile/projectile.dm
Labels: Bugfix, Work in Progress

#1034 Cooking patch map
  maps/CEVEris/_CEV_Eris.dmm
Labels: Bugfix, Map Changes
