Repository Occulus-Server/Occulus-Eris, pull requests merged in 2023-01, with the labels that each got.

#939 Revert "Fixes Zoom Function"
  code/modules/mob/mob.dm
Labels: Priority: High, Ready to Merge, Revert

#938 Bumps DreamAnnotate to v2
  .github/workflows/ci_suite.yml
Labels: Ready to Merge, Github/Discord

#940 Makes adminlogs properly say who received an email
  code/modules/modular_computers/file_system/programs/generic/email_client.dm
Labels: Bugfix, Ready to Merge

#942 Vote windows will now close properly
  code/controllers/subsystems/vote.dm
Labels: Priority: High, Bugfix, Ready to Merge, Revert

#941 No law zero'd drones
  code/game/antagonist/station/rogue_ai.dm
Labels: Bugfix, Ready to Merge

#920 Revamps the Mekhane ElectroMace
  zzzz_modular_occulus/code/game/objects/items/weapons/design_disks/mekhane.dm
  zzzz_modular_occulus/icons/obj/mek_melee.dmi
Labels: Feature, Sprites, Modular, Ready for review

#944 Revert Accessory Update
  cev_eris.dme
  code/modules/clothing/spacesuits/void/void.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/modules/client/preference_setup/loadout/lists/accessories.dm
  zzzz_modular_occulus/code/modules/clothing/accessories/accessory.dm
  zzzz_modular_occulus/code/modules/clothing/clothing.dm
  zzzz_modular_occulus/code/modules/clothing/masks/masks.dm
  zzzz_modular_occulus/code/modules/clothing/spacesuits/void/void.dm
  zzzz_modular_occulus/code/modules/clothing/suit/storage.dm
  zzzz_modular_occulus/code/modules/clothing/suit/suits.dm
  zzzz_modular_occulus/icons/inventory/accessory/icon.dmi
  zzzz_modular_occulus/icons/inventory/accessory/mob.dmi
Labels: Removal

#945 Revert "Revert Accessory Update"
  cev_eris.dme
  code/modules/clothing/spacesuits/void/void.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/code/modules/client/preference_setup/loadout/lists/accessories.dm
  zzzz_modular_occulus/code/modules/clothing/accessories/accessory.dm
  zzzz_modular_occulus/code/modules/clothing/clothing.dm
  zzzz_modular_occulus/code/modules/clothing/masks/masks.dm
  zzzz_modular_occulus/code/modules/clothing/spacesuits/void/void.dm
  zzzz_modular_occulus/code/modules/clothing/suit/storage.dm
  zzzz_modular_occulus/code/modules/clothing/suit/suits.dm
  zzzz_modular_occulus/icons/inventory/accessory/icon.dmi
  zzzz_modular_occulus/icons/inventory/accessory/mob.dmi
Labels: Quality of Life, Modular, Ready to Merge
