Repository Occulus-Server/Occulus-Eris, pull requests merged in 2023-09, with the labels that each got.

#1058 Update ADMS.dm
  zzzz_modular_occulus/code/modules/maint_expeditions/ADMS.dm
Labels: Balance/Rebalance

#1059 Nemesis Assault strider Buff
  zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/nemesis.dm
Labels: Ready for review, Balance/Rebalance

#1060 Deepmaint Adjustments
  code/modules/dungeons/procedural/deepmaint.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzzz_modular_occulus/maps/submaps/deepmaint_rooms/normal/normal_rooms.dm
  zzzz_modular_occulus/maps/submaps/deepmaint_rooms/normal/oopsallslimes.dmm
  zzzz_modular_occulus/maps/submaps/deepmaint_rooms/normal/oopsallspooders.dmm
  zzzz_modular_occulus/maps/submaps/deepmaint_rooms/normal/roachracer.dmm
  zzzz_modular_occulus/maps/submaps/deepmaint_rooms/normal/worstnightmare.dmm
Labels: Balance/Rebalance, Bugfix, Map Changes
