Repository Occulus-Server/Occulus-Eris, pull requests merged in 2023-04, with the labels that each got.

#954 Adjustment to critical APCs
  code/modules/power/apc.dm
Labels: Ready for review, Balance/Rebalance

#958 Hub Visibility Toggle & Restricted Observation
  code/game/world.dm
  code/modules/admin/admin.dm
  code/modules/mob/new_player/new_player.dm
Labels: Priority: High, Ready for review, Administrative

#966 fixes overlap between Shoudin and Jive
  code/modules/mob/language/station.dm
Labels: Bugfix

#964 Benzin Nerfs
  cev_eris.dme
  code/modules/mob/living/carbon/superior_animal/roach/types/benzin.dm
Labels: Priority: High, Ready for review, Balance/Rebalance
